/* AUTO-GENERATED by lms/tools/build_catalog.py from LMS_PLAN.md. Do not edit by hand. */
window.LMS_CATALOG = {
 "generatedFrom": "LMS_PLAN.md",
 "paths": [
  {
   "id": "P1",
   "name": "Full Architect Path",
   "modules": "All modules M00–M45",
   "hours": "~230 h (about 6 months at 10 h/week)",
   "outcome": "Certification + architect portfolio"
  },
  {
   "id": "P2",
   "name": "SAA-C03 Exam Path",
   "modules": "M00–M35, M43, M45",
   "hours": "~150 h provisional; 15 weeks at 10 h/week, excluding optional tracks",
   "outcome": "Certification preparation"
  },
  {
   "id": "P3",
   "name": "DevOps & IaC Path",
   "modules": "M01, M03, M05, M09, M13, M16, M30, M36–M39, M44 capstone",
   "hours": "~70 h",
   "outcome": "IaC + CI/CD practitioner"
  },
  {
   "id": "P4",
   "name": "System Design Path",
   "modules": "M04, M40, M41, M42, plus service modules as needed",
   "hours": "~60 h",
   "outcome": "System design interview / architect readiness"
  },
  {
   "id": "P5",
   "name": "Elective: AI Agents on AWS",
   "modules": "M46",
   "hours": "~15 h",
   "outcome": "Agentic architecture awareness"
  }
 ],
 "tracks": [
  {
   "id": "A",
   "title": "Foundations (Level 100)",
   "modules": [
    {
     "id": "M00",
     "title": "Orientation, exam blueprint and study skills",
     "track": "A",
     "levels": "100",
     "hours": "2 h",
     "exam": "all domains",
     "prereqs": [],
     "lessons": [
      {
       "id": "M00.01",
       "title": "How this academy works",
       "level": "100",
       "concepts": "Paths, levels, badges, gating, how to use labs safely"
      },
      {
       "id": "M00.02",
       "title": "The SAA-C03 exam",
       "level": "100",
       "concepts": "65 questions (50 scored + 15 unscored), 130 minutes, 720/1000 to pass, compensatory scoring, domain weights 30/26/24/20"
      },
      {
       "id": "M00.03",
       "title": "How AWS exam questions are built",
       "level": "200",
       "concepts": "Scenario stem, constraint keywords (\"most cost-effective\", \"least operational overhead\"), plausible distractors, multiple-response questions"
      },
      {
       "id": "M00.04",
       "title": "Learning science",
       "level": "100",
       "concepts": "Spaced repetition, active recall, decision tables, error log"
      },
      {
       "id": "M00.05",
       "title": "Diagnostic test",
       "level": "–",
       "concepts": "Pilot: 20 questions (6/5/5/4 by domain), about 30 minutes; saves missed answers and study links. Planned expansion: 40 calibrated questions."
      }
     ]
    },
    {
     "id": "M01",
     "title": "Cloud computing and the AWS global infrastructure",
     "track": "A",
     "levels": "100–200",
     "hours": "4 h",
     "exam": "Tasks 1.1, 2.2, 4.2",
     "prereqs": [
      "M00"
     ],
     "lessons": [
      {
       "id": "M01.01",
       "title": "What is cloud computing",
       "level": "100",
       "concepts": "IaaS/PaaS/SaaS, CapEx vs OpEx, elasticity, the 6 advantages of cloud"
      },
      {
       "id": "M01.02",
       "title": "Global infrastructure",
       "level": "100",
       "concepts": "Regions, AZs, edge locations, Local Zones, Wavelength Zones, Outposts; choosing a Region (compliance, latency, service availability, cost)"
      },
      {
       "id": "M01.03",
       "title": "Shared responsibility model",
       "level": "100",
       "concepts": "Security \"of\" vs \"in\" the cloud; how the split changes for EC2 vs RDS vs Lambda"
      },
      {
       "id": "M01.04",
       "title": "Accessing AWS",
       "level": "100",
       "concepts": "Management Console, AWS CLI, SDKs, CloudShell, the API-driven nature of AWS"
      },
      {
       "id": "M01.05",
       "title": "Pricing fundamentals",
       "level": "200",
       "concepts": "Pay-as-you-go, Free Tier, data-transfer pricing basics, the Pricing Calculator"
      },
      {
       "id": "M01.06",
       "title": "Well-Architected Framework intro",
       "level": "200",
       "concepts": "The 6 pillars, design principles, the WA Tool (detailed in M43)"
      }
     ]
    },
    {
     "id": "M02",
     "title": "Networking fundamentals (before AWS)",
     "track": "A",
     "levels": "100–200",
     "hours": "5 h",
     "exam": "Tasks 1.2, 3.4",
     "prereqs": [],
     "lessons": [
      {
       "id": "M02.01",
       "title": "OSI and TCP/IP models",
       "level": "100",
       "concepts": "Layers 3/4/7, why load balancers are \"L4\" or \"L7\""
      },
      {
       "id": "M02.02",
       "title": "IP addressing and CIDR",
       "level": "100",
       "concepts": "IPv4, private ranges (RFC 1918), CIDR math, subnetting practice, IPv6 basics"
      },
      {
       "id": "M02.03",
       "title": "Routing and NAT",
       "level": "100",
       "concepts": "Default routes, route tables, NAT/PAT, public vs private IPs"
      },
      {
       "id": "M02.04",
       "title": "DNS",
       "level": "100",
       "concepts": "Record types (A, AAAA, CNAME, MX, TXT, NS), TTL, resolvers, the CNAME-at-apex problem"
      },
      {
       "id": "M02.05",
       "title": "TCP, UDP, HTTP(S), TLS",
       "level": "200",
       "concepts": "Handshakes, ports, HTTP/1.1 vs HTTP/2, WebSockets, gRPC, TLS termination, certificates"
      },
      {
       "id": "M02.06",
       "title": "VPNs, firewalls, proxies",
       "level": "200",
       "concepts": "IPsec, stateful vs stateless filtering, forward vs reverse proxy"
      }
     ]
    },
    {
     "id": "M03",
     "title": "Linux, CLI and tooling essentials",
     "track": "A",
     "levels": "100",
     "hours": "3 h",
     "exam": "supporting",
     "prereqs": [],
     "lessons": [
      {
       "id": "M03.01",
       "title": "Linux essentials for cloud",
       "level": "100",
       "concepts": "SSH, permissions, packages, systemd, logs"
      },
      {
       "id": "M03.02",
       "title": "AWS CLI in depth",
       "level": "200",
       "concepts": "Profiles, --query (JMESPath), output formats, pagination, SSO login"
      },
      {
       "id": "M03.03",
       "title": "Git and YAML/JSON",
       "level": "100",
       "concepts": "Git workflow, YAML pitfalls, JSON policy syntax"
      },
      {
       "id": "M03.04",
       "title": "Developer environment",
       "level": "100",
       "concepts": "VS Code, Node/Python for CDK, Docker basics"
      }
     ]
    },
    {
     "id": "M04",
     "title": "System design fundamentals",
     "track": "A",
     "levels": "100–300",
     "hours": "8 h",
     "exam": "Tasks 2.1, 2.2, 3.x",
     "prereqs": [
      "M02"
     ],
     "lessons": [
      {
       "id": "M04.01",
       "title": "Thinking like an architect",
       "level": "100",
       "concepts": "Functional vs non-functional requirements, SLAs/SLOs/SLIs, the \"nines\" of availability, back-of-envelope estimation"
      },
      {
       "id": "M04.02",
       "title": "Scalability",
       "level": "100",
       "concepts": "Vertical vs horizontal scaling, stateless vs stateful services, session externalisation"
      },
      {
       "id": "M04.03",
       "title": "Availability and reliability",
       "level": "200",
       "concepts": "Redundancy, single points of failure (SPOF), failover, MTTR/MTBF, RPO/RTO"
      },
      {
       "id": "M04.04",
       "title": "Consistency and CAP/PACELC",
       "level": "200",
       "concepts": "Strong vs eventual consistency, quorum, CAP theorem, PACELC"
      },
      {
       "id": "M04.05",
       "title": "Latency, throughput, performance",
       "level": "200",
       "concepts": "Latency numbers every engineer should know, percentiles (p99), bottlenecks"
      },
      {
       "id": "M04.06",
       "title": "Fallacies of distributed computing",
       "level": "200",
       "concepts": "The 8 fallacies and the AWS features that mitigate each"
      },
      {
       "id": "M04.07",
       "title": "Data storage formats",
       "level": "200",
       "concepts": "Block vs file vs object; row vs columnar; OLTP vs OLAP"
      },
      {
       "id": "M04.08",
       "title": "Monolith → SOA → microservices",
       "level": "200",
       "concepts": "Service boundaries, coupling, multi-tier architectures"
      },
      {
       "id": "M04.09",
       "title": "Trade-off framework",
       "level": "300",
       "concepts": "Cost vs performance vs reliability; writing an Architecture Decision Record (ADR)"
      }
     ]
    }
   ]
  },
  {
   "id": "B",
   "title": "Security (Exam Domain 1: 30%)",
   "modules": [
    {
     "id": "M05",
     "title": "Identity and Access Management (IAM)",
     "track": "B",
     "levels": "100–400",
     "hours": "8 h",
     "exam": "Task 1.1",
     "prereqs": [
      "M01"
     ],
     "lessons": [
      {
       "id": "M05.01",
       "title": "IAM fundamentals",
       "level": "100",
       "concepts": "Principals, users, groups, roles, policies; root user best practices; MFA"
      },
      {
       "id": "M05.02",
       "title": "Policy language",
       "level": "200",
       "concepts": "JSON structure (Effect, Action, Resource, Condition, Principal), wildcards, policy variables"
      },
      {
       "id": "M05.03",
       "title": "Policy types",
       "level": "200",
       "concepts": "Identity-based, resource-based, permission boundaries, SCPs, session policies, ACLs"
      },
      {
       "id": "M05.04",
       "title": "Policy evaluation logic",
       "level": "300",
       "concepts": "Explicit deny → allow → implicit deny; same-account vs cross-account evaluation"
      },
      {
       "id": "M05.05",
       "title": "Roles and STS",
       "level": "200",
       "concepts": "AssumeRole, instance profiles, service-linked roles, temporary credentials"
      },
      {
       "id": "M05.06",
       "title": "Cross-account access patterns",
       "level": "300",
       "concepts": "Role switching, resource policies vs roles, the External ID / confused deputy problem"
      },
      {
       "id": "M05.07",
       "title": "Federation",
       "level": "300",
       "concepts": "SAML 2.0, OIDC, web identity, IAM Identity Center with an external IdP or AD"
      },
      {
       "id": "M05.08",
       "title": "Attribute-based access control (ABAC)",
       "level": "400",
       "concepts": "Tag-based access control, scaling permissions with tags"
      },
      {
       "id": "M05.09",
       "title": "Least privilege in practice",
       "level": "300",
       "concepts": "IAM Access Analyzer, last-accessed data, credential reports, policy generation"
      },
      {
       "id": "M05.10",
       "title": "Application identity: Amazon Cognito",
       "level": "200",
       "concepts": "User pools vs identity pools, hosted UI, JWTs, social sign-in"
      }
     ]
    },
    {
     "id": "M06",
     "title": "Multi-account strategy and governance",
     "track": "B",
     "levels": "200–400",
     "hours": "6 h",
     "exam": "Task 1.1",
     "prereqs": [
      "M05"
     ],
     "lessons": [
      {
       "id": "M06.01",
       "title": "Why multiple accounts",
       "level": "200",
       "concepts": "Blast radius, billing separation, environment isolation"
      },
      {
       "id": "M06.02",
       "title": "AWS Organizations",
       "level": "200",
       "concepts": "OUs, consolidated billing, volume discounts, delegated administrator"
      },
      {
       "id": "M06.03",
       "title": "Service control policies (SCPs)",
       "level": "300",
       "concepts": "Guardrails (SCPs never grant permissions), deny-list vs allow-list, Region restriction, protecting security tooling"
      },
      {
       "id": "M06.04",
       "title": "AWS Control Tower",
       "level": "300",
       "concepts": "Landing zone, Account Factory, preventive/detective/proactive controls"
      },
      {
       "id": "M06.05",
       "title": "IAM Identity Center at scale",
       "level": "300",
       "concepts": "Permission sets, account assignments, AD/IdP integration"
      },
      {
       "id": "M06.06",
       "title": "AWS Directory Service",
       "level": "200",
       "concepts": "AWS Managed Microsoft AD vs AD Connector vs Simple AD; trusts"
      },
      {
       "id": "M06.07",
       "title": "Resource sharing",
       "level": "300",
       "concepts": "AWS RAM (subnets, Transit Gateways, license configurations), centralised networking accounts"
      },
      {
       "id": "M06.08",
       "title": "Reference multi-account architecture",
       "level": "400",
       "concepts": "Security, Log Archive, Shared Services, Network, workload OUs (AWS Security Reference Architecture)"
      }
     ]
    },
    {
     "id": "M07",
     "title": "Data protection and encryption",
     "track": "B",
     "levels": "200–400",
     "hours": "7 h",
     "exam": "Task 1.3",
     "prereqs": [
      "M05"
     ],
     "lessons": [
      {
       "id": "M07.01",
       "title": "Encryption fundamentals",
       "level": "100",
       "concepts": "Symmetric vs asymmetric, at rest vs in transit, hashing"
      },
      {
       "id": "M07.02",
       "title": "AWS KMS",
       "level": "200",
       "concepts": "KMS keys: AWS-owned vs AWS-managed vs customer-managed; envelope encryption, data keys"
      },
      {
       "id": "M07.03",
       "title": "KMS key policies and grants",
       "level": "300",
       "concepts": "Key policy + IAM interplay, cross-account key use, grants, multi-Region keys"
      },
      {
       "id": "M07.04",
       "title": "Key rotation and lifecycle",
       "level": "300",
       "concepts": "Automatic vs manual rotation, imported key material, deletion waiting period"
      },
      {
       "id": "M07.05",
       "title": "CloudHSM",
       "level": "300",
       "concepts": "Single-tenant HSM, FIPS requirements, when to choose it over KMS"
      },
      {
       "id": "M07.06",
       "title": "Encryption per service",
       "level": "300",
       "concepts": "S3 (SSE-S3, SSE-KMS, DSSE-KMS, SSE-C, client-side), EBS, RDS (encrypting an unencrypted DB via snapshot copy), DynamoDB"
      },
      {
       "id": "M07.07",
       "title": "Encryption in transit",
       "level": "200",
       "concepts": "ACM public vs private certificates, auto-renewal, TLS on ALB/CloudFront/API Gateway, certificate Region rules (CloudFront uses us-east-1)"
      },
      {
       "id": "M07.08",
       "title": "Secrets management",
       "level": "200",
       "concepts": "Secrets Manager (rotation via Lambda) vs SSM Parameter Store (SecureString)"
      },
      {
       "id": "M07.09",
       "title": "Data governance and compliance",
       "level": "300",
       "concepts": "Data classification, retention, Macie, AWS Artifact, Config conformance packs, S3 Object Lock (governance vs compliance mode)"
      },
      {
       "id": "M07.10",
       "title": "Backup as data protection",
       "level": "300",
       "concepts": "AWS Backup plans, vault lock, cross-account/cross-Region copies (detailed in M20)"
      }
     ]
    },
    {
     "id": "M08",
     "title": "Threat protection, detection and perimeter security",
     "track": "B",
     "levels": "100–400",
     "hours": "8 h",
     "exam": "Task 1.2 (with 1.3 access-control reinforcement)",
     "prereqs": [
      "M05"
     ],
     "lessons": [
      {
       "id": "M08.01",
       "title": "Threats from outside AWS",
       "level": "100",
       "concepts": "DDoS (L3/4 vs L7), SQL injection, XSS, bots, credential stuffing"
      },
      {
       "id": "M08.02",
       "title": "AWS Shield",
       "level": "200",
       "concepts": "Standard vs Advanced, DDoS Response Team, cost protection"
      },
      {
       "id": "M08.03",
       "title": "AWS WAF",
       "level": "300",
       "concepts": "Web ACLs, managed rule groups, rate-based rules, geo-match; attaching to CloudFront/ALB/API Gateway/AppSync/Cognito"
      },
      {
       "id": "M08.04",
       "title": "AWS Network Firewall and Firewall Manager",
       "level": "300",
       "concepts": "Stateful inspection, inspection VPC patterns, central policy across accounts"
      },
      {
       "id": "M08.05",
       "title": "Detection services",
       "level": "200",
       "concepts": "GuardDuty (threat detection), Inspector (vulnerabilities), Macie (PII in S3), Detective (investigation), Security Hub (aggregation)"
      },
      {
       "id": "M08.06",
       "title": "Audit and configuration",
       "level": "200",
       "concepts": "CloudTrail (API audit, organisation trail, log file validation), AWS Config (rules, remediation, resource history)"
      },
      {
       "id": "M08.07",
       "title": "Secure application access",
       "level": "300",
       "concepts": "Endpoints, private APIs, presigned URLs, CloudFront signed URLs/cookies"
      },
      {
       "id": "M08.08",
       "title": "Incident response basics",
       "level": "400",
       "concepts": "EventBridge + Lambda automated remediation, isolating a compromised instance"
      }
     ]
    }
   ]
  },
  {
   "id": "C",
   "title": "Networking (Exam Domain 3: 24%)",
   "modules": [
    {
     "id": "M09",
     "title": "Amazon VPC core",
     "track": "C",
     "levels": "100–400",
     "hours": "12 h",
     "exam": "Tasks 1.2, 3.4, 4.4",
     "prereqs": [
      "M02"
     ],
     "lessons": [
      {
       "id": "M09.01",
       "title": "VPC anatomy",
       "level": "100",
       "concepts": "VPC, CIDR planning, reserved IPs per subnet, default VPC"
      },
      {
       "id": "M09.02",
       "title": "Subnets and route tables",
       "level": "200",
       "concepts": "Public vs private subnets, the main route table, subnet tiers (web/app/data)"
      },
      {
       "id": "M09.03",
       "title": "Internet access",
       "level": "200",
       "concepts": "Internet Gateway, Elastic IPs, egress-only IGW (IPv6)"
      },
      {
       "id": "M09.04",
       "title": "NAT",
       "level": "300",
       "concepts": "Public/private NAT; zonal vs regional availability mode; NAT instances; same-AZ routing, egress cost and failure dependencies"
      },
      {
       "id": "M09.05",
       "title": "Security groups vs NACLs",
       "level": "200",
       "concepts": "Stateful vs stateless, allow-only vs allow/deny, rule ordering, SG referencing"
      },
      {
       "id": "M09.06",
       "title": "Bastions and Session Manager",
       "level": "200",
       "concepts": "Removing SSH exposure, SSM Session Manager, EC2 Instance Connect Endpoint"
      },
      {
       "id": "M09.07",
       "title": "VPC Flow Logs and Reachability Analyzer",
       "level": "300",
       "concepts": "Troubleshooting traffic, log destinations"
      },
      {
       "id": "M09.08",
       "title": "IPv6 and IP address management",
       "level": "400",
       "concepts": "Dual-stack, current subnet sizing, DNS64/NAT64, IPAM governance and avoiding CIDR overlap"
      }
     ]
    },
    {
     "id": "M10",
     "title": "VPC connectivity and private access",
     "track": "C",
     "levels": "200–400",
     "hours": "8 h",
     "exam": "Tasks 1.2, 3.4, 4.4",
     "prereqs": [
      "M09"
     ],
     "lessons": [
      {
       "id": "M10.01",
       "title": "VPC peering",
       "level": "200",
       "concepts": "Non-transitive, no overlapping CIDRs, cross-account/cross-Region peering"
      },
      {
       "id": "M10.02",
       "title": "AWS Transit Gateway",
       "level": "300",
       "concepts": "Hub-and-spoke, route tables, attachments, inter-Region peering, sharing via RAM"
      },
      {
       "id": "M10.03",
       "title": "VPC endpoints",
       "level": "300",
       "concepts": "Gateway endpoints (S3/DynamoDB, free) vs interface endpoints (ENIs, charged); endpoint policies"
      },
      {
       "id": "M10.04",
       "title": "AWS PrivateLink",
       "level": "300",
       "concepts": "Exposing a service via NLB + endpoint service; SaaS pattern; works with overlapping CIDRs"
      },
      {
       "id": "M10.05",
       "title": "Network cost optimisation",
       "level": "300",
       "concepts": "Cross-AZ charges, NAT processing charges, using endpoints to avoid NAT, centralised egress"
      },
      {
       "id": "M10.06",
       "title": "VPC Lattice (awareness)",
       "level": "400",
       "concepts": "Service-to-service networking (beyond the exam)"
      }
     ]
    },
    {
     "id": "M11",
     "title": "Hybrid connectivity",
     "track": "C",
     "levels": "200–300",
     "hours": "4 h",
     "exam": "Tasks 1.2, 3.4, 4.4",
     "prereqs": [
      "M09",
      "M10"
     ],
     "lessons": [
      {
       "id": "M11.01",
       "title": "AWS Site-to-Site VPN",
       "level": "200",
       "concepts": "Virtual private gateway vs Transit Gateway termination, two tunnels, BGP vs static routing, accelerated VPN"
      },
      {
       "id": "M11.02",
       "title": "AWS Client VPN",
       "level": "200",
       "concepts": "Remote user access, authentication options"
      },
      {
       "id": "M11.03",
       "title": "AWS Direct Connect",
       "level": "300",
       "concepts": "Dedicated vs hosted connections, VIF types (private/public/transit), DX Gateway, LAG, MACsec, lead time"
      },
      {
       "id": "M11.04",
       "title": "Resilient hybrid designs",
       "level": "300",
       "concepts": "DX + VPN backup, dual DX for maximum resiliency, bandwidth sizing"
      },
      {
       "id": "M11.05",
       "title": "Hybrid DNS",
       "level": "400",
       "concepts": "Route 53 Resolver inbound/outbound endpoints, forwarding rules"
      }
     ]
    },
    {
     "id": "M12",
     "title": "DNS, edge and load balancing",
     "track": "C",
     "levels": "200–400",
     "hours": "8 h",
     "exam": "Tasks 2.1, 2.2, 3.4, 4.4",
     "prereqs": [
      "M09"
     ],
     "lessons": [
      {
       "id": "M12.01",
       "title": "Amazon Route 53",
       "level": "200",
       "concepts": "Hosted zones (public/private), alias vs CNAME, domain registration"
      },
      {
       "id": "M12.02",
       "title": "Route 53 routing policies",
       "level": "300",
       "concepts": "Simple, weighted, latency, failover, geolocation, geoproximity, IP-based, multivalue answer; health checks"
      },
      {
       "id": "M12.03",
       "title": "Elastic Load Balancing",
       "level": "200",
       "concepts": "ALB (L7: path/host/header routing, Lambda targets), NLB (L4: static IP, TLS passthrough, extreme performance), GWLB (appliances, GENEVE)"
      },
      {
       "id": "M12.04",
       "title": "ELB in depth",
       "level": "300",
       "concepts": "Target groups, health checks, cross-zone load balancing, sticky sessions, connection draining, SNI"
      },
      {
       "id": "M12.05",
       "title": "Amazon CloudFront",
       "level": "300",
       "concepts": "Origins, behaviours, cache keys/policies, TTLs, OAC for S3, signed URLs/cookies, field-level encryption, Lambda@Edge vs CloudFront Functions"
      },
      {
       "id": "M12.06",
       "title": "AWS Global Accelerator",
       "level": "300",
       "concepts": "Anycast static IPs, TCP/UDP, fast Regional failover; vs CloudFront"
      },
      {
       "id": "M12.07",
       "title": "Load-balancing algorithms and theory",
       "level": "300",
       "concepts": "Round robin, least connections, consistent hashing, L4 vs L7 trade-offs"
      },
      {
       "id": "M12.08",
       "title": "Global architectures",
       "level": "400",
       "concepts": "Multi-Region active-active with Route 53 + Global Accelerator, latency-based routing to Regional stacks"
      }
     ]
    }
   ]
  },
  {
   "id": "D",
   "title": "Compute (Exam Domain 3: 24%)",
   "modules": [
    {
     "id": "M13",
     "title": "Amazon EC2 in depth",
     "track": "D",
     "levels": "100–400",
     "hours": "8 h",
     "exam": "Tasks 3.2, 4.2",
     "prereqs": [
      "M09"
     ],
     "lessons": [
      {
       "id": "M13.01",
       "title": "EC2 basics",
       "level": "100",
       "concepts": "AMIs, instance lifecycle, key pairs, user data, instance metadata (IMDSv2)"
      },
      {
       "id": "M13.02",
       "title": "Instance types",
       "level": "200",
       "concepts": "Families (general purpose M/T, compute C, memory R/X, storage I/D, accelerated P/G/Inf/Trn), sizes, burstable credits, Graviton"
      },
      {
       "id": "M13.03",
       "title": "Purchasing options",
       "level": "300",
       "concepts": "On-Demand, Savings Plans (Compute vs EC2 Instance), Reserved Instances (standard vs convertible), Spot (interruptions, Spot Fleet), Dedicated Hosts vs Dedicated Instances, Capacity Reservations"
      },
      {
       "id": "M13.04",
       "title": "Placement and networking",
       "level": "300",
       "concepts": "Cluster/spread/partition placement groups, ENIs, ENA, EFA"
      },
      {
       "id": "M13.05",
       "title": "Instance storage choices",
       "level": "200",
       "concepts": "EBS-backed vs instance store (see M19)"
      },
      {
       "id": "M13.06",
       "title": "Hibernate, stop, terminate",
       "level": "200",
       "concepts": "Hibernation use cases, termination protection"
      },
      {
       "id": "M13.07",
       "title": "Golden AMIs and immutable infrastructure",
       "level": "400",
       "concepts": "EC2 Image Builder, replace-don't-patch, AMI sharing/copying across Regions"
      },
      {
       "id": "M13.08",
       "title": "Licensing and hybrid compute",
       "level": "300",
       "concepts": "License Manager, Dedicated Hosts for BYOL, Outposts, VMware Cloud on AWS"
      }
     ]
    },
    {
     "id": "M14",
     "title": "Elasticity and Auto Scaling",
     "track": "D",
     "levels": "200–300",
     "hours": "5 h",
     "exam": "Tasks 2.1, 3.2, 4.2",
     "prereqs": [
      "M12",
      "M13"
     ],
     "lessons": [
      {
       "id": "M14.01",
       "title": "Amazon EC2 Auto Scaling",
       "level": "200",
       "concepts": "Launch templates, min/desired/max, ASG health checks (EC2 vs ELB)"
      },
      {
       "id": "M14.02",
       "title": "Scaling policies",
       "level": "300",
       "concepts": "Target tracking, step, simple, scheduled, predictive; cooldowns and warm-up"
      },
      {
       "id": "M14.03",
       "title": "Scaling on the right metric",
       "level": "300",
       "concepts": "CPU vs request count vs SQS backlog per instance; custom metrics"
      },
      {
       "id": "M14.04",
       "title": "Lifecycle hooks, warm pools, instance refresh",
       "level": "300",
       "concepts": "Graceful bootstrap/shutdown, rolling AMI updates"
      },
      {
       "id": "M14.05",
       "title": "AWS Auto Scaling (application level)",
       "level": "300",
       "concepts": "Scaling plans for DynamoDB, ECS, Aurora replicas"
      },
      {
       "id": "M14.06",
       "title": "Elasticity patterns",
       "level": "300",
       "concepts": "Decoupling with queues so tiers scale independently"
      }
     ]
    },
    {
     "id": "M15",
     "title": "Containers on AWS",
     "track": "D",
     "levels": "200–400",
     "hours": "8 h",
     "exam": "Tasks 2.1, 3.2, 4.2",
     "prereqs": [
      "M13"
     ],
     "lessons": [
      {
       "id": "M15.01",
       "title": "Containers 101",
       "level": "100",
       "concepts": "Images, registries, Dockerfiles, container vs VM"
      },
      {
       "id": "M15.02",
       "title": "Amazon ECR",
       "level": "200",
       "concepts": "Private/public repositories, image scanning, lifecycle policies, cross-Region replication"
      },
      {
       "id": "M15.03",
       "title": "Amazon ECS",
       "level": "200",
       "concepts": "Clusters, task definitions, services, task roles vs execution roles"
      },
      {
       "id": "M15.04",
       "title": "Launch types",
       "level": "300",
       "concepts": "EC2 vs Fargate (operational overhead vs control vs cost), Fargate Spot, capacity providers"
      },
      {
       "id": "M15.05",
       "title": "Amazon EKS",
       "level": "300",
       "concepts": "Control plane, managed node groups, Fargate profiles, Karpenter (awareness), IRSA / Pod Identity"
      },
      {
       "id": "M15.06",
       "title": "Hybrid containers",
       "level": "300",
       "concepts": "ECS Anywhere, EKS Anywhere, EKS Distro"
      },
      {
       "id": "M15.07",
       "title": "Migrating applications to containers",
       "level": "300",
       "concepts": "Lift-and-containerise, App2Container (awareness), 12-factor apps"
      },
      {
       "id": "M15.08",
       "title": "Container orchestration theory",
       "level": "400",
       "concepts": "Scheduling, service discovery, rolling vs blue/green deployments"
      }
     ]
    },
    {
     "id": "M16",
     "title": "Serverless compute and APIs",
     "track": "D",
     "levels": "200–400",
     "hours": "8 h",
     "exam": "Tasks 2.1, 3.2, 4.2",
     "prereqs": [
      "M05"
     ],
     "lessons": [
      {
       "id": "M16.01",
       "title": "AWS Lambda fundamentals",
       "level": "200",
       "concepts": "Event sources, invocation types (synchronous/asynchronous/polling), memory (which also sets CPU), 15-minute limit, /tmp"
      },
      {
       "id": "M16.02",
       "title": "Lambda scaling and performance",
       "level": "300",
       "concepts": "Concurrency, reserved vs provisioned concurrency, cold starts, SnapStart, Lambda in a VPC"
      },
      {
       "id": "M16.03",
       "title": "Lambda reliability",
       "level": "300",
       "concepts": "Retries, DLQs and destinations, idempotency, batch failure handling for SQS/Kinesis"
      },
      {
       "id": "M16.04",
       "title": "Amazon API Gateway",
       "level": "200",
       "concepts": "REST vs HTTP vs WebSocket APIs, stages, integrations"
      },
      {
       "id": "M16.05",
       "title": "API Gateway in depth",
       "level": "300",
       "concepts": "Throttling and usage plans, caching, authorisers (IAM/Cognito/Lambda), private APIs, edge-optimised vs regional endpoints"
      },
      {
       "id": "M16.06",
       "title": "Front-end and mobile",
       "level": "200",
       "concepts": "AWS Amplify hosting/backends, AppSync (GraphQL) awareness, AWS Device Farm"
      },
      {
       "id": "M16.07",
       "title": "Serverless patterns",
       "level": "300",
       "concepts": "API → Lambda → DynamoDB, the Serverless Application Repository, when NOT to use serverless"
      },
      {
       "id": "M16.08",
       "title": "Serverless cost model",
       "level": "300",
       "concepts": "Lambda vs Fargate vs EC2 break-even analysis"
      }
     ]
    },
    {
     "id": "M17",
     "title": "Other compute services",
     "track": "D",
     "levels": "200–300",
     "hours": "3 h",
     "exam": "Tasks 3.2, 4.2",
     "prereqs": [
      "M13"
     ],
     "lessons": [
      {
       "id": "M17.01",
       "title": "AWS Elastic Beanstalk",
       "level": "200",
       "concepts": "PaaS; deployment policies (all-at-once, rolling, rolling with batch, immutable, traffic splitting, blue/green via CNAME swap)"
      },
      {
       "id": "M17.02",
       "title": "AWS Batch",
       "level": "300",
       "concepts": "Job queues, compute environments, Spot for batch jobs; vs Lambda vs EMR"
      },
      {
       "id": "M17.03",
       "title": "Edge and hybrid compute",
       "level": "300",
       "concepts": "Outposts, Wavelength, Local Zones, Snowball Edge compute, VMware Cloud on AWS"
      },
      {
       "id": "M17.04",
       "title": "Choosing compute",
       "level": "300",
       "concepts": "Decision tree: EC2 / ECS / EKS / Fargate / Lambda / Batch / Beanstalk"
      }
     ]
    }
   ]
  },
  {
   "id": "E",
   "title": "Storage (Exam Domain 3: 24%)",
   "modules": [
    {
     "id": "M18",
     "title": "Amazon S3 from beginner to expert",
     "track": "E",
     "levels": "100–400",
     "hours": "9 h",
     "exam": "Tasks 1.3, 3.1, 4.1",
     "prereqs": [
      "M05"
     ],
     "lessons": [
      {
       "id": "M18.01",
       "title": "S3 fundamentals",
       "level": "100",
       "concepts": "Buckets, objects, keys, prefixes, durability (11 nines) vs availability, strong consistency"
      },
      {
       "id": "M18.02",
       "title": "Storage classes",
       "level": "200",
       "concepts": "Standard, Intelligent-Tiering, Standard-IA, One Zone-IA, Glacier Instant/Flexible Retrieval, Deep Archive; minimum storage durations, retrieval fees, Express One Zone"
      },
      {
       "id": "M18.03",
       "title": "Lifecycle management",
       "level": "300",
       "concepts": "Transition and expiration rules, noncurrent versions, incomplete multipart upload cleanup"
      },
      {
       "id": "M18.04",
       "title": "Security",
       "level": "300",
       "concepts": "Block Public Access, bucket policies vs IAM vs ACLs (disabled by default), Object Ownership, VPC endpoint policies, Access Points"
      },
      {
       "id": "M18.05",
       "title": "Versioning, replication, Object Lock",
       "level": "300",
       "concepts": "CRR vs SRR, Replication Time Control, Object Lock modes, MFA Delete"
      },
      {
       "id": "M18.06",
       "title": "Performance",
       "level": "300",
       "concepts": "Prefix parallelism, multipart upload, byte-range fetches, Transfer Acceleration, S3 Select (legacy)"
      },
      {
       "id": "M18.07",
       "title": "Access patterns and cost",
       "level": "300",
       "concepts": "Requester Pays, presigned URLs, batch vs individual uploads, S3 Storage Lens, Inventory"
      },
      {
       "id": "M18.08",
       "title": "Events and integrations",
       "level": "300",
       "concepts": "Event notifications → SNS/SQS/Lambda/EventBridge, static website hosting"
      },
      {
       "id": "M18.09",
       "title": "S3 at scale",
       "level": "400",
       "concepts": "S3 Batch Operations, Multi-Region Access Points, data-lake foundations"
      }
     ]
    },
    {
     "id": "M19",
     "title": "Block and file storage",
     "track": "E",
     "levels": "200–300",
     "hours": "5 h",
     "exam": "Tasks 3.1, 4.1",
     "prereqs": [
      "M13"
     ],
     "lessons": [
      {
       "id": "M19.01",
       "title": "Amazon EBS",
       "level": "200",
       "concepts": "Volume types: gp3 (IOPS/throughput set independently of size), io2 Block Express, st1, sc1; AZ-scoped volumes"
      },
      {
       "id": "M19.02",
       "title": "EBS operations",
       "level": "300",
       "concepts": "Snapshots (incremental, cross-Region copy), Fast Snapshot Restore, encryption, Multi-Attach, Elastic Volumes, Data Lifecycle Manager"
      },
      {
       "id": "M19.03",
       "title": "Instance store",
       "level": "200",
       "concepts": "Ephemeral storage, very high IOPS, data lost on stop/terminate"
      },
      {
       "id": "M19.04",
       "title": "Amazon EFS",
       "level": "300",
       "concepts": "NFS, multi-AZ vs One Zone, performance/throughput modes, storage classes and lifecycle, access points"
      },
      {
       "id": "M19.05",
       "title": "Amazon FSx",
       "level": "300",
       "concepts": "FSx for Windows File Server (SMB, AD), Lustre (HPC, S3-linked), NetApp ONTAP (multi-protocol), OpenZFS"
      },
      {
       "id": "M19.06",
       "title": "Choosing storage",
       "level": "300",
       "concepts": "Decision matrix: object vs block vs file, performance vs cost"
      }
     ]
    },
    {
     "id": "M20",
     "title": "Hybrid storage, data transfer and backup",
     "track": "E",
     "levels": "200–300",
     "hours": "5 h",
     "exam": "Tasks 3.1, 3.5, 4.1",
     "prereqs": [
      "M18",
      "M19"
     ],
     "lessons": [
      {
       "id": "M20.01",
       "title": "AWS Storage Gateway",
       "level": "300",
       "concepts": "S3 File Gateway, FSx File Gateway, Volume Gateway (cached vs stored), Tape Gateway"
      },
      {
       "id": "M20.02",
       "title": "AWS DataSync",
       "level": "300",
       "concepts": "Online transfer NFS/SMB/HDFS/S3 ↔ AWS, scheduling, bandwidth throttling"
      },
      {
       "id": "M20.03",
       "title": "AWS Transfer Family",
       "level": "200",
       "concepts": "Managed SFTP/FTPS/FTP/AS2 onto S3/EFS"
      },
      {
       "id": "M20.04",
       "title": "AWS Snow Family",
       "level": "300",
       "concepts": "Snowball Edge (current device options), when offline transfer beats the network (transfer-time maths)"
      },
      {
       "id": "M20.05",
       "title": "AWS Backup",
       "level": "300",
       "concepts": "Backup plans, vaults, Vault Lock, cross-Region/cross-account copies, Organizations backup policies"
      },
      {
       "id": "M20.06",
       "title": "Choosing a transfer method",
       "level": "300",
       "concepts": "Data size × bandwidth × time window → Snow vs DataSync vs DX vs S3 Transfer Acceleration"
      }
     ]
    }
   ]
  },
  {
   "id": "F",
   "title": "Databases (Exam Domain 3: 24%)",
   "modules": [
    {
     "id": "M21",
     "title": "Relational databases: RDS and Aurora",
     "track": "F",
     "levels": "100–400",
     "hours": "9 h",
     "exam": "Tasks 2.1, 2.2, 3.3, 4.3",
     "prereqs": [
      "M09"
     ],
     "lessons": [
      {
       "id": "M21.01",
       "title": "Relational fundamentals",
       "level": "100",
       "concepts": "ACID, normalisation, indexes, transactions, isolation levels"
      },
      {
       "id": "M21.02",
       "title": "Amazon RDS",
       "level": "200",
       "concepts": "Engines (MySQL, PostgreSQL, MariaDB, Oracle, SQL Server, Db2), instance classes, storage types, parameter groups"
      },
      {
       "id": "M21.03",
       "title": "High availability",
       "level": "300",
       "concepts": "Multi-AZ instance (synchronous standby) vs Multi-AZ DB cluster (readable standbys), failover behaviour"
      },
      {
       "id": "M21.04",
       "title": "Read replicas",
       "level": "300",
       "concepts": "Asynchronous replication, cross-Region replicas, promotion; read scaling vs DR"
      },
      {
       "id": "M21.05",
       "title": "Backups and recovery",
       "level": "300",
       "concepts": "Automated backups + PITR, manual snapshots, snapshot sharing/copying, retention design"
      },
      {
       "id": "M21.06",
       "title": "Amazon Aurora",
       "level": "300",
       "concepts": "Cluster storage (6 copies across 3 AZs), reader/writer endpoints, custom endpoints, Backtrack, cloning"
      },
      {
       "id": "M21.07",
       "title": "Aurora Serverless v2 and Global Database",
       "level": "300",
       "concepts": "ACU-based scaling, cross-Region replication with < 1 s typical lag, managed failover"
      },
      {
       "id": "M21.08",
       "title": "Connections and proxies",
       "level": "300",
       "concepts": "RDS Proxy (connection pooling for Lambda, faster failover, IAM auth)"
      },
      {
       "id": "M21.09",
       "title": "Engine choice and capacity planning",
       "level": "300",
       "concepts": "MySQL vs PostgreSQL, Provisioned IOPS, storage auto scaling, Performance Insights"
      },
      {
       "id": "M21.10",
       "title": "Scaling relational at scale",
       "level": "400",
       "concepts": "Sharding, partitioning, CQRS, read/write splitting"
      }
     ]
    },
    {
     "id": "M22",
     "title": "NoSQL and purpose-built databases",
     "track": "F",
     "levels": "100–400",
     "hours": "8 h",
     "exam": "Tasks 3.3, 4.3",
     "prereqs": [
      "M04"
     ],
     "lessons": [
      {
       "id": "M22.01",
       "title": "NoSQL concepts",
       "level": "100",
       "concepts": "Key-value, document, wide-column, graph; BASE; when to choose NoSQL"
      },
      {
       "id": "M22.02",
       "title": "DynamoDB fundamentals",
       "level": "200",
       "concepts": "Tables, items, partition/sort keys, 400 KB item limit, eventually vs strongly consistent reads"
      },
      {
       "id": "M22.03",
       "title": "DynamoDB capacity",
       "level": "300",
       "concepts": "On-demand vs provisioned (RCU/WCU maths), auto scaling, hot partitions, adaptive capacity"
      },
      {
       "id": "M22.04",
       "title": "DynamoDB indexes and access patterns",
       "level": "300",
       "concepts": "GSI vs LSI, single-table design, query vs scan"
      },
      {
       "id": "M22.05",
       "title": "DynamoDB advanced features",
       "level": "300",
       "concepts": "Streams, TTL, transactions, global tables (multi-Region active-active), PITR, export to S3, DAX"
      },
      {
       "id": "M22.06",
       "title": "Amazon DocumentDB",
       "level": "200",
       "concepts": "MongoDB-compatible document database"
      },
      {
       "id": "M22.07",
       "title": "Amazon Keyspaces",
       "level": "200",
       "concepts": "Cassandra-compatible, serverless"
      },
      {
       "id": "M22.08",
       "title": "Amazon Neptune",
       "level": "200",
       "concepts": "Graph database (social graphs, fraud detection, knowledge graphs)"
      },
      {
       "id": "M22.09",
       "title": "Choosing the database",
       "level": "300",
       "concepts": "Decision matrix: RDS/Aurora/DynamoDB/DocumentDB/Keyspaces/Neptune/Redshift/ElastiCache/OpenSearch"
      }
     ]
    },
    {
     "id": "M23",
     "title": "Caching",
     "track": "F",
     "levels": "200–400",
     "hours": "5 h",
     "exam": "Tasks 2.1, 3.3, 4.3",
     "prereqs": [
      "M21",
      "M22"
     ],
     "lessons": [
      {
       "id": "M23.01",
       "title": "Why cache",
       "level": "100",
       "concepts": "Latency, offloading the database, cost"
      },
      {
       "id": "M23.02",
       "title": "Eviction and invalidation",
       "level": "200",
       "concepts": "LRU/LFU/FIFO, TTL, cache stampede"
      },
      {
       "id": "M23.03",
       "title": "Caching strategies",
       "level": "300",
       "concepts": "Cache-aside (lazy loading), write-through, write-behind, read-through"
      },
      {
       "id": "M23.04",
       "title": "Amazon ElastiCache",
       "level": "300",
       "concepts": "Redis OSS / Valkey vs Memcached; cluster mode, replication, Multi-AZ, serverless option"
      },
      {
       "id": "M23.05",
       "title": "Caching at every layer",
       "level": "300",
       "concepts": "CloudFront, API Gateway cache, DAX, application caches; session stores"
      },
      {
       "id": "M23.06",
       "title": "Distributed caching at scale",
       "level": "400",
       "concepts": "Consistent hashing, hot keys, cache warming"
      }
     ]
    },
    {
     "id": "M24",
     "title": "Database migration",
     "track": "F",
     "levels": "300",
     "hours": "3 h",
     "exam": "Tasks 3.3, 4.3",
     "prereqs": [
      "M21"
     ],
     "lessons": [
      {
       "id": "M24.01",
       "title": "Homogeneous vs heterogeneous migration",
       "level": "300",
       "concepts": "Native tools vs DMS; when the Schema Conversion Tool is needed"
      },
      {
       "id": "M24.02",
       "title": "AWS DMS",
       "level": "300",
       "concepts": "Replication instances, endpoints, full load + CDC, DMS Serverless"
      },
      {
       "id": "M24.03",
       "title": "Migration patterns",
       "level": "300",
       "concepts": "Oracle → Aurora PostgreSQL, on-premises MySQL → RDS, minimal-downtime cutover"
      }
     ]
    }
   ]
  },
  {
   "id": "G",
   "title": "Application integration",
   "modules": [
    {
     "id": "M25",
     "title": "Messaging and events",
     "track": "G",
     "levels": "200–400",
     "hours": "7 h",
     "exam": "Tasks 2.1, 3.2",
     "prereqs": [
      "M16"
     ],
     "lessons": [
      {
       "id": "M25.01",
       "title": "Why decouple",
       "level": "100",
       "concepts": "Synchronous vs asynchronous, back-pressure, loose coupling"
      },
      {
       "id": "M25.02",
       "title": "Amazon SQS",
       "level": "200",
       "concepts": "Standard vs FIFO (ordering, exactly-once processing, message groups), visibility timeout, long polling, retention, DLQs, delay queues"
      },
      {
       "id": "M25.03",
       "title": "SQS patterns",
       "level": "300",
       "concepts": "Worker fleets, scaling on backlog, large payloads via S3 (extended client)"
      },
      {
       "id": "M25.04",
       "title": "Amazon SNS",
       "level": "200",
       "concepts": "Topics, subscriptions, filter policies, FIFO topics, fan-out to SQS"
      },
      {
       "id": "M25.05",
       "title": "Amazon EventBridge",
       "level": "300",
       "concepts": "Event buses, rules and patterns, schema registry, archive/replay, Pipes, Scheduler, cross-account buses"
      },
      {
       "id": "M25.06",
       "title": "Amazon MQ",
       "level": "200",
       "concepts": "ActiveMQ/RabbitMQ for lift-and-shift of existing brokers"
      },
      {
       "id": "M25.07",
       "title": "Amazon AppFlow",
       "level": "200",
       "concepts": "SaaS ↔ AWS data flows (Salesforce, etc.)"
      },
      {
       "id": "M25.08",
       "title": "Choosing a messaging service",
       "level": "300",
       "concepts": "SQS vs SNS vs EventBridge vs Kinesis vs MQ decision matrix"
      }
     ]
    },
    {
     "id": "M26",
     "title": "Workflow orchestration and event-driven architecture",
     "track": "G",
     "levels": "300–400",
     "hours": "6 h",
     "exam": "Task 2.1",
     "prereqs": [
      "M25"
     ],
     "lessons": [
      {
       "id": "M26.01",
       "title": "AWS Step Functions",
       "level": "300",
       "concepts": "Standard vs Express workflows, states, error handling and retries, service integrations, human approval"
      },
      {
       "id": "M26.02",
       "title": "Choreography vs orchestration",
       "level": "300",
       "concepts": "Trade-offs, when to use each"
      },
      {
       "id": "M26.03",
       "title": "Event-driven architecture",
       "level": "300",
       "concepts": "Events vs commands, event sourcing, idempotent consumers"
      },
      {
       "id": "M26.04",
       "title": "Distributed transaction patterns",
       "level": "400",
       "concepts": "Saga (orchestrated/choreographed), outbox, CQRS, change data capture"
      },
      {
       "id": "M26.05",
       "title": "Microservice design principles",
       "level": "300",
       "concepts": "Stateless services, service boundaries, API-first design, strangler fig migration"
      }
     ]
    }
   ]
  },
  {
   "id": "H",
   "title": "Data, analytics and ML (Exam Domain 3: 24%)",
   "modules": [
    {
     "id": "M27",
     "title": "Streaming data",
     "track": "H",
     "levels": "200–400",
     "hours": "5 h",
     "exam": "Task 3.5",
     "prereqs": [
      "M25"
     ],
     "lessons": [
      {
       "id": "M27.01",
       "title": "Batch vs streaming",
       "level": "100",
       "concepts": "Ingestion frequency, latency requirements"
      },
      {
       "id": "M27.02",
       "title": "Amazon Kinesis Data Streams",
       "level": "300",
       "concepts": "Shards, partition keys, provisioned vs on-demand modes, retention, enhanced fan-out, ordering"
      },
      {
       "id": "M27.03",
       "title": "Amazon Data Firehose",
       "level": "300",
       "concepts": "Near-real-time delivery to S3/Redshift/OpenSearch/HTTP, buffering, Lambda transforms, Parquet conversion"
      },
      {
       "id": "M27.04",
       "title": "Amazon MSK",
       "level": "300",
       "concepts": "Managed Kafka, MSK Serverless, when to choose it over Kinesis"
      },
      {
       "id": "M27.05",
       "title": "Kinesis Video Streams and media",
       "level": "200",
       "concepts": "Video ingestion, Rekognition Video integration, Elastic Transcoder (legacy)"
      },
      {
       "id": "M27.06",
       "title": "Stream processing architectures",
       "level": "400",
       "concepts": "Lambda vs Managed Service for Apache Flink (awareness), exactly-once processing, windowing"
      }
     ]
    },
    {
     "id": "M28",
     "title": "Data lakes and analytics",
     "track": "H",
     "levels": "200–400",
     "hours": "7 h",
     "exam": "Task 3.5",
     "prereqs": [
      "M18"
     ],
     "lessons": [
      {
       "id": "M28.01",
       "title": "Data lake fundamentals",
       "level": "200",
       "concepts": "Raw/processed/curated zones on S3, partitioning, columnar formats (Parquet, ORC)"
      },
      {
       "id": "M28.02",
       "title": "AWS Glue",
       "level": "300",
       "concepts": "Crawlers, Data Catalog, ETL jobs, converting CSV → Parquet, Glue DataBrew (awareness)"
      },
      {
       "id": "M28.03",
       "title": "AWS Lake Formation",
       "level": "300",
       "concepts": "Centralised permissions, fine-grained (column/row) access, securing the lake"
      },
      {
       "id": "M28.04",
       "title": "Amazon Athena",
       "level": "300",
       "concepts": "Serverless SQL on S3, cost per data scanned, partitioning to reduce cost, federated queries"
      },
      {
       "id": "M28.05",
       "title": "Amazon EMR",
       "level": "300",
       "concepts": "Hadoop/Spark clusters, EMR Serverless, Spot for task nodes"
      },
      {
       "id": "M28.06",
       "title": "Amazon Redshift",
       "level": "300",
       "concepts": "Columnar data warehouse, Redshift Serverless, Spectrum, RA3 nodes, concurrency scaling"
      },
      {
       "id": "M28.07",
       "title": "Amazon OpenSearch Service",
       "level": "200",
       "concepts": "Search and log analytics"
      },
      {
       "id": "M28.08",
       "title": "Amazon Quick (formerly QuickSight) and AWS Data Exchange",
       "level": "200",
       "concepts": "BI dashboards; subscribing to third-party data"
      },
      {
       "id": "M28.09",
       "title": "Big data reference architectures",
       "level": "400",
       "concepts": "Lambda vs Kappa architecture, lakehouse"
      }
     ]
    },
    {
     "id": "M29",
     "title": "AI/ML services (exam scope)",
     "track": "H",
     "levels": "100–200",
     "hours": "3 h",
     "exam": "Tasks 2.2, 3.5",
     "prereqs": [],
     "lessons": [
      {
       "id": "M29.01",
       "title": "AI service catalogue",
       "level": "100",
       "concepts": "Comprehend (NLP/sentiment/PII), Lex (chatbots), Polly (text-to-speech), Rekognition (image/video), Textract (documents), Transcribe (speech-to-text), Translate"
      },
      {
       "id": "M29.02",
       "title": "Amazon SageMaker AI",
       "level": "200",
       "concepts": "Build/train/deploy managed ML; when to use it vs the pre-trained AI services"
      },
      {
       "id": "M29.03",
       "title": "Use-case matching drill",
       "level": "200",
       "concepts": "\"Extract text from scanned invoices\" → Textract, etc."
      },
      {
       "id": "M29.04",
       "title": "Generative AI awareness",
       "level": "200",
       "concepts": "Bedrock (beyond the exam), links to the M46 elective"
      }
     ]
    }
   ]
  },
  {
   "id": "I",
   "title": "Operations and governance",
   "modules": [
    {
     "id": "M30",
     "title": "Monitoring and observability",
     "track": "I",
     "levels": "200–400",
     "hours": "5 h",
     "exam": "Task 2.2",
     "prereqs": [
      "M13"
     ],
     "lessons": [
      {
       "id": "M30.01",
       "title": "Amazon CloudWatch metrics and alarms",
       "level": "200",
       "concepts": "Standard vs detailed monitoring, custom metrics, the CloudWatch agent (memory/disk), composite alarms"
      },
      {
       "id": "M30.02",
       "title": "CloudWatch Logs",
       "level": "200",
       "concepts": "Log groups, retention, metric filters, Logs Insights, subscriptions"
      },
      {
       "id": "M30.03",
       "title": "AWS X-Ray and tracing",
       "level": "300",
       "concepts": "Traces, segments, service map; finding latency bottlenecks"
      },
      {
       "id": "M30.04",
       "title": "Managed Grafana and Managed Service for Prometheus",
       "level": "200",
       "concepts": "Container/EKS observability"
      },
      {
       "id": "M30.05",
       "title": "AWS Health Dashboard",
       "level": "200",
       "concepts": "Service health vs account-specific events, EventBridge integration"
      },
      {
       "id": "M30.06",
       "title": "Designing observability",
       "level": "400",
       "concepts": "The three pillars of observability, SLO-based alerting, dashboards for business metrics"
      }
     ]
    },
    {
     "id": "M31",
     "title": "Management and governance tools",
     "track": "I",
     "levels": "200–300",
     "hours": "5 h",
     "exam": "Tasks 2.2, 4.x",
     "prereqs": [
      "M06"
     ],
     "lessons": [
      {
       "id": "M31.01",
       "title": "AWS Systems Manager",
       "level": "300",
       "concepts": "Session Manager, Run Command, Patch Manager, State Manager, Parameter Store, Automation runbooks, Fleet Manager"
      },
      {
       "id": "M31.02",
       "title": "AWS Config in depth",
       "level": "300",
       "concepts": "Managed/custom rules, conformance packs, aggregators, auto-remediation"
      },
      {
       "id": "M31.03",
       "title": "AWS Service Catalog",
       "level": "200",
       "concepts": "Approved product portfolios, self-service with guardrails"
      },
      {
       "id": "M31.04",
       "title": "Trusted Advisor and Compute Optimizer",
       "level": "200",
       "concepts": "Checks by category, rightsizing recommendations"
      },
      {
       "id": "M31.05",
       "title": "Service Quotas and throttling",
       "level": "300",
       "concepts": "Quotas vs limits, quota increases in the DR Region, API throttling and exponential backoff"
      },
      {
       "id": "M31.06",
       "title": "License Manager and the Well-Architected Tool",
       "level": "200",
       "concepts": "BYOL tracking, workload reviews"
      }
     ]
    }
   ]
  },
  {
   "id": "J",
   "title": "Resilience, DR and migration (Exam Domain 2: 26%)",
   "modules": [
    {
     "id": "M32",
     "title": "High availability and fault-tolerance patterns",
     "track": "J",
     "levels": "300–400",
     "hours": "6 h",
     "exam": "Task 2.2",
     "prereqs": [
      "M12",
      "M14",
      "M21"
     ],
     "lessons": [
      {
       "id": "M32.01",
       "title": "Designing out single points of failure",
       "level": "300",
       "concepts": "Multi-AZ everything; stateless tiers; managed services with built-in HA"
      },
      {
       "id": "M32.02",
       "title": "Failover strategies",
       "level": "300",
       "concepts": "Active-passive vs active-active, DNS failover, health checks at every layer"
      },
      {
       "id": "M32.03",
       "title": "Distributed design patterns",
       "level": "400",
       "concepts": "Retries with backoff and jitter, timeouts, circuit breaker, bulkhead, load shedding, static stability, cell-based architecture"
      },
      {
       "id": "M32.04",
       "title": "Improving legacy applications without code changes",
       "level": "300",
       "concepts": "Put an ALB/ASG in front, move state to EFS/ElastiCache, RDS Multi-AZ, Route 53 health checks"
      },
      {
       "id": "M32.05",
       "title": "Immutable infrastructure and automation",
       "level": "300",
       "concepts": "Replace rather than repair, IaC drift detection, self-healing ASGs"
      },
      {
       "id": "M32.06",
       "title": "Chaos engineering awareness",
       "level": "400",
       "concepts": "Game days, AWS Fault Injection Service (beyond the exam)"
      }
     ]
    },
    {
     "id": "M33",
     "title": "Disaster recovery and migration",
     "track": "J",
     "levels": "300–400",
     "hours": "6 h",
     "exam": "Task 2.2",
     "prereqs": [
      "M32"
     ],
     "lessons": [
      {
       "id": "M33.01",
       "title": "RPO and RTO",
       "level": "200",
       "concepts": "Defining business requirements, cost vs recovery speed"
      },
      {
       "id": "M33.02",
       "title": "The four DR strategies",
       "level": "300",
       "concepts": "Backup & restore → pilot light → warm standby → multi-site active-active; matching each to RPO/RTO targets"
      },
      {
       "id": "M33.03",
       "title": "Multi-Region building blocks",
       "level": "300",
       "concepts": "S3 CRR, Aurora Global, DynamoDB global tables, Route 53 ARC (awareness), AMI/snapshot copies, KMS multi-Region keys"
      },
      {
       "id": "M33.04",
       "title": "AWS Elastic Disaster Recovery",
       "level": "300",
       "concepts": "Continuous block-level replication, low-cost staging area"
      },
      {
       "id": "M33.05",
       "title": "Cloud migration strategies",
       "level": "300",
       "concepts": "The 7 Rs (retire, retain, rehost, relocate, repurchase, replatform, refactor); AWS Application Migration Service; Migration Hub (awareness)"
      },
      {
       "id": "M33.06",
       "title": "DR runbooks and testing",
       "level": "400",
       "concepts": "Failover drills, Service Quotas in the standby Region, DNS TTL planning"
      }
     ]
    }
   ]
  },
  {
   "id": "K",
   "title": "Cost optimisation (Exam Domain 4: 20%)",
   "modules": [
    {
     "id": "M34",
     "title": "Cost-optimised architectures",
     "track": "K",
     "levels": "200–400",
     "hours": "7 h",
     "exam": "Tasks 4.1–4.4",
     "prereqs": [
      "M13",
      "M18",
      "M21"
     ],
     "lessons": [
      {
       "id": "M34.01",
       "title": "Cost management tools",
       "level": "200",
       "concepts": "Cost Explorer, AWS Budgets (and budget actions), Cost and Usage Report / Data Exports, cost allocation tags, consolidated billing"
      },
      {
       "id": "M34.02",
       "title": "Compute cost",
       "level": "300",
       "concepts": "Rightsizing, Savings Plans vs RIs, Spot strategies, Graviton, auto scaling/scheduling for non-production"
      },
      {
       "id": "M34.03",
       "title": "Storage cost",
       "level": "300",
       "concepts": "S3 class selection, lifecycle, Intelligent-Tiering, EBS gp3, deleting orphaned snapshots"
      },
      {
       "id": "M34.04",
       "title": "Database cost",
       "level": "300",
       "concepts": "Serverless vs provisioned, DynamoDB on-demand vs provisioned, reserved DB instances, caching to downsize"
      },
      {
       "id": "M34.05",
       "title": "Network and data-transfer cost",
       "level": "300",
       "concepts": "Cross-AZ/cross-Region transfer, NAT processing, VPC endpoints, CloudFront to reduce egress, DX vs VPN cost"
      },
      {
       "id": "M34.06",
       "title": "Workload classes",
       "level": "300",
       "concepts": "Different availability and cost targets for production vs non-production"
      },
      {
       "id": "M34.07",
       "title": "FinOps practice",
       "level": "400",
       "concepts": "Showback/chargeback, unit economics, anomaly detection"
      }
     ]
    },
    {
     "id": "M35",
     "title": "Domain synthesis: scenario workshops",
     "track": "K",
     "levels": "300",
     "hours": "6 h",
     "exam": "all",
     "prereqs": [
      "M05",
      "M06",
      "M07",
      "M08",
      "M09",
      "M10",
      "M11",
      "M12",
      "M13",
      "M14",
      "M15",
      "M16",
      "M17",
      "M18",
      "M19",
      "M20",
      "M21",
      "M22",
      "M23",
      "M24",
      "M25",
      "M26",
      "M27",
      "M28",
      "M29",
      "M30",
      "M31",
      "M32",
      "M33",
      "M34"
     ],
     "lessons": [
      {
       "id": "M35.01",
       "title": "Secure architecture scenarios",
       "level": "300",
       "concepts": "30 timed scenario questions + walkthroughs"
      },
      {
       "id": "M35.02",
       "title": "Resilient architecture scenarios",
       "level": "300",
       "concepts": "30 timed scenario questions + walkthroughs"
      },
      {
       "id": "M35.03",
       "title": "High-performing architecture scenarios",
       "level": "300",
       "concepts": "30 timed scenario questions + walkthroughs"
      },
      {
       "id": "M35.04",
       "title": "Cost-optimised architecture scenarios",
       "level": "300",
       "concepts": "30 timed scenario questions + walkthroughs"
      },
      {
       "id": "M35.05",
       "title": "\"Improve this architecture\" clinics",
       "level": "300",
       "concepts": "Review a flawed diagram, list issues per Well-Architected pillar"
      }
     ]
    }
   ]
  },
  {
   "id": "L",
   "title": "DevOps and Infrastructure as Code (Level 200–400)",
   "modules": [
    {
     "id": "M36",
     "title": "IaC fundamentals and AWS CloudFormation",
     "track": "L",
     "levels": "200–300",
     "hours": "7 h",
     "exam": "Task 2.2 (automation, immutable infrastructure)",
     "prereqs": [
      "M09"
     ],
     "lessons": [
      {
       "id": "M36.01",
       "title": "Why IaC",
       "level": "100",
       "concepts": "Repeatability, review, drift, declarative vs imperative"
      },
      {
       "id": "M36.02",
       "title": "CloudFormation templates",
       "level": "200",
       "concepts": "Resources, Parameters, Mappings, Conditions, Outputs, intrinsic functions"
      },
      {
       "id": "M36.03",
       "title": "Stacks in practice",
       "level": "300",
       "concepts": "Change sets, rollback, DeletionPolicy/UpdateReplacePolicy, drift detection, termination protection"
      },
      {
       "id": "M36.04",
       "title": "Multi-stack and multi-account",
       "level": "300",
       "concepts": "Nested stacks, cross-stack references (Exports), StackSets with Organizations"
      },
      {
       "id": "M36.05",
       "title": "Custom resources and macros",
       "level": "400",
       "concepts": "Lambda-backed custom resources"
      },
      {
       "id": "M36.06",
       "title": "IaC for governance",
       "level": "300",
       "concepts": "Service Catalog products from templates, CloudFormation Guard / cfn-lint"
      }
     ]
    },
    {
     "id": "M37",
     "title": "AWS CDK",
     "track": "L",
     "levels": "200–400",
     "hours": "10 h",
     "exam": "indirect (CDK is out of scope; it compiles to CloudFormation)",
     "prereqs": [
      "M36"
     ],
     "lessons": [
      {
       "id": "M37.01",
       "title": "Hello CDK",
       "level": "200",
       "concepts": "App → Stack → Construct, cdk init/synth/diff/deploy, bootstrapping"
      },
      {
       "id": "M37.02",
       "title": "Construct levels",
       "level": "200",
       "concepts": "L1 (Cfn*), L2 (intent-based), L3 (patterns); when to use each"
      },
      {
       "id": "M37.03",
       "title": "Integrating constructs",
       "level": "300",
       "concepts": "Grants (bucket.grantRead), parameters, context, overrides/escape hatches"
      },
      {
       "id": "M37.04",
       "title": "Multi-stack applications",
       "level": "300",
       "concepts": "Cross-stack references, environments, stage-per-account"
      },
      {
       "id": "M37.05",
       "title": "Packaging Lambda functions",
       "level": "300",
       "concepts": "NodejsFunction/bundling, assets, layers"
      },
      {
       "id": "M37.06",
       "title": "Custom constructs",
       "level": "400",
       "concepts": "Extending constructs, publishing a reusable construct library"
      },
      {
       "id": "M37.07",
       "title": "Custom resources and third-party constructs",
       "level": "400",
       "concepts": "AwsCustomResource, Construct Hub"
      },
      {
       "id": "M37.08",
       "title": "Testing CDK apps",
       "level": "400",
       "concepts": "Jest snapshot + fine-grained assertions, cdk-nag security rules, pre-commit hooks"
      },
      {
       "id": "M37.09",
       "title": "CDK vs Terraform vs CloudFormation",
       "level": "300",
       "concepts": "Selection criteria, multicloud considerations"
      }
     ]
    },
    {
     "id": "M38",
     "title": "CI/CD and DevSecOps",
     "track": "L",
     "levels": "300–400",
     "hours": "8 h",
     "exam": "Tasks 1.2, 2.2 (deployment strategies, credentials security)",
     "prereqs": [
      "M37"
     ],
     "lessons": [
      {
       "id": "M38.01",
       "title": "CI/CD fundamentals",
       "level": "200",
       "concepts": "Continuous integration vs delivery vs deployment, trunk-based development vs Gitflow, artefacts"
      },
      {
       "id": "M38.02",
       "title": "Pipelines on GitHub Actions",
       "level": "300",
       "concepts": "Workflows, environments, OIDC federation to an IAM role (no long-lived keys)"
      },
      {
       "id": "M38.03",
       "title": "AWS-native pipelines (awareness)",
       "level": "300",
       "concepts": "CodePipeline, CodeBuild, CodeDeploy (out of exam scope, common in jobs), CDK Pipelines"
      },
      {
       "id": "M38.04",
       "title": "Deployment strategies",
       "level": "300",
       "concepts": "Rolling, blue/green, canary, linear, feature flags; Lambda aliases + traffic shifting; ECS blue/green"
      },
      {
       "id": "M38.05",
       "title": "DevSecOps",
       "level": "400",
       "concepts": "SAST, dependency scanning, container image scanning (ECR/Inspector), cdk-nag gates, secrets in pipelines"
      },
      {
       "id": "M38.06",
       "title": "Release safety",
       "level": "400",
       "concepts": "Automated rollback on CloudWatch alarms, change windows, deployment documentation"
      }
     ]
    },
    {
     "id": "M39",
     "title": "Terraform essentials (elective)",
     "track": "L",
     "levels": "200–300",
     "hours": "5 h",
     "exam": "none",
     "prereqs": [
      "M36"
     ],
     "lessons": [
      {
       "id": "M39.01",
       "title": "Terraform basics",
       "level": "200",
       "concepts": "Providers, resources, variables, outputs, plan/apply"
      },
      {
       "id": "M39.02",
       "title": "State management",
       "level": "300",
       "concepts": "Remote state in S3 with locking, workspaces"
      },
      {
       "id": "M39.03",
       "title": "Modules and environments",
       "level": "300",
       "concepts": "Reusable modules, the AWS provider, multi-account layouts"
      }
     ]
    }
   ]
  },
  {
   "id": "M",
   "title": "System design (Level 300–400)",
   "modules": [
    {
     "id": "M40",
     "title": "Distributed systems patterns",
     "track": "M",
     "levels": "300–400",
     "hours": "8 h",
     "exam": "Tasks 2.1, 2.2",
     "prereqs": [
      "M04",
      "M25"
     ],
     "lessons": [
      {
       "id": "M40.01",
       "title": "Data partitioning and replication",
       "level": "400",
       "concepts": "Sharding strategies, consistent hashing, leader/follower vs leaderless replication, quorum"
      },
      {
       "id": "M40.02",
       "title": "Communication patterns",
       "level": "300",
       "concepts": "REST vs gRPC vs GraphQL vs WebSockets, long polling, server-sent events"
      },
      {
       "id": "M40.03",
       "title": "Rate limiting and throttling",
       "level": "400",
       "concepts": "Token bucket, leaky bucket, API Gateway/WAF implementations"
      },
      {
       "id": "M40.04",
       "title": "Idempotency and delivery guarantees",
       "level": "400",
       "concepts": "At-most-once, at-least-once, exactly-once; deduplication"
      },
      {
       "id": "M40.05",
       "title": "Cloud architecture patterns",
       "level": "300",
       "concepts": "Strangler fig, sidecar, ambassador, anti-corruption layer, CQRS, event sourcing"
      },
      {
       "id": "M40.06",
       "title": "Search, IDs and counters",
       "level": "400",
       "concepts": "Inverted indexes, unique ID generation (Snowflake-style IDs), distributed counters"
      },
      {
       "id": "M40.07",
       "title": "Open-source distributed systems on AWS",
       "level": "400",
       "concepts": "Kafka, Cassandra, Elasticsearch, Redis vs their managed AWS equivalents"
      }
     ]
    },
    {
     "id": "M41",
     "title": "System design method and interview framework",
     "track": "M",
     "levels": "300",
     "hours": "3 h",
     "exam": "",
     "prereqs": [
      "M40"
     ],
     "lessons": [
      {
       "id": "M41.01",
       "title": "The 4-step design method",
       "level": "300",
       "concepts": "Requirements → estimates → high-level design → deep dive and bottlenecks"
      },
      {
       "id": "M41.02",
       "title": "Capacity estimation",
       "level": "300",
       "concepts": "QPS, storage and bandwidth maths"
      },
      {
       "id": "M41.03",
       "title": "Presenting a design",
       "level": "300",
       "concepts": "Diagrams, ADRs, trade-off narration"
      }
     ]
    },
    {
     "id": "M42",
     "title": "System design case studies (on AWS)",
     "track": "M",
     "levels": "300–400",
     "hours": "24 h (3 h per case)",
     "exam": "",
     "prereqs": [
      "M41"
     ],
     "lessons": [
      {
       "id": "M42.01",
       "title": "URL shortener",
       "level": "300",
       "concepts": "Hashing, base62, read-heavy caching, redirects · Services: API Gateway, Lambda, DynamoDB, CloudFront, ElastiCache · Source: SD ch.14 (p667)"
      },
      {
       "id": "M42.02",
       "title": "Web crawler & search engine",
       "level": "300",
       "concepts": "Politeness, frontier queues, dedup, inverted index · Services: SQS, ECS/Batch, S3, OpenSearch · Source: SD ch.15 (p726)"
      },
      {
       "id": "M42.03",
       "title": "Social network & newsfeed",
       "level": "300",
       "concepts": "Fan-out-on-write vs fan-out-on-read, the celebrity problem, graph · Services: Neptune, DynamoDB, ElastiCache, SNS/SQS · Source: SD ch.16 (p777)"
      },
      {
       "id": "M42.04",
       "title": "Online game leaderboard",
       "level": "300",
       "concepts": "Sorted sets, real-time ranking, sharding · Services: ElastiCache Redis, DynamoDB, Kinesis · Source: SD ch.17 (p826)"
      },
      {
       "id": "M42.05",
       "title": "Hotel reservation",
       "level": "300",
       "concepts": "Concurrency control, double booking, transactions, idempotency · Services: Aurora, RDS Proxy, SQS FIFO, Step Functions · Source: SD ch.18 (p872)"
      },
      {
       "id": "M42.06",
       "title": "Chat application",
       "level": "300",
       "concepts": "WebSockets, presence, message ordering, offline delivery · Services: API Gateway WebSocket, DynamoDB, ElastiCache, SNS · Source: SD ch.19 (p905)"
      },
      {
       "id": "M42.07",
       "title": "Video-processing pipeline",
       "level": "300",
       "concepts": "Transcoding, chunking, DAG workflows, CDN delivery · Services: S3, Step Functions, Batch/ECS, CloudFront · Source: SD ch.20 (p949)"
      },
      {
       "id": "M42.08",
       "title": "Stock-trading platform",
       "level": "300",
       "concepts": "Low latency, ordering, strong consistency, audit, matching engine · Services: EC2 placement groups, MSK/Kinesis, Aurora, DynamoDB · Source: SD ch.21 (p982)"
      }
     ]
    }
   ]
  },
  {
   "id": "N",
   "title": "Well-Architected, capstones and exam readiness",
   "modules": [
    {
     "id": "M43",
     "title": "AWS Well-Architected Framework in depth",
     "track": "N",
     "levels": "300",
     "hours": "4 h",
     "exam": "all",
     "prereqs": [
      "M35"
     ],
     "lessons": [
      {
       "id": "M43.01",
       "title": "Operational Excellence",
       "level": "300",
       "concepts": "IaC, small reversible changes, runbooks, learning from failure"
      },
      {
       "id": "M43.02",
       "title": "Security",
       "level": "300",
       "concepts": "Identity foundation, traceability, defence in depth, data protection"
      },
      {
       "id": "M43.03",
       "title": "Reliability",
       "level": "300",
       "concepts": "Automatic recovery, horizontal scaling, stop guessing capacity"
      },
      {
       "id": "M43.04",
       "title": "Performance Efficiency",
       "level": "300",
       "concepts": "Advanced technologies as managed services, going global, serverless, experimentation"
      },
      {
       "id": "M43.05",
       "title": "Cost Optimization",
       "level": "300",
       "concepts": "Cloud financial management, consumption model, measuring efficiency"
      },
      {
       "id": "M43.06",
       "title": "Sustainability",
       "level": "300",
       "concepts": "Utilisation, managed services, Graviton, data lifecycle"
      },
      {
       "id": "M43.07",
       "title": "Running a WA review",
       "level": "400",
       "concepts": "WA Tool, lenses (Serverless, SaaS), creating an improvement plan"
      }
     ]
    },
    {
     "id": "M44",
     "title": "Capstone projects",
     "track": "N",
     "levels": "400",
     "hours": "30 h",
     "exam": "",
     "prereqs": [],
     "lessons": [
      {
       "id": "M44.01",
       "title": "Capstone C1: Highly available 3-tier web app",
       "level": "400",
       "concepts": "VPC (3 tiers, 2 AZs), ALB + ASG/ECS, Aurora Multi-AZ, ElastiCache, CloudFront + WAF, all in IaC · Assessed on: HA design, security groups, cost estimate, IaC quality"
      },
      {
       "id": "M44.02",
       "title": "Capstone C2: Serverless event-driven order system",
       "level": "400",
       "concepts": "API Gateway, Lambda, SQS/SNS/EventBridge, Step Functions saga, DynamoDB; CDK + GitHub Actions CI/CD with a canary · Assessed on: Decoupling, idempotency, tests, pipeline"
      },
      {
       "id": "M44.03",
       "title": "Capstone C3: Analytics data lake",
       "level": "400",
       "concepts": "Kinesis/Firehose ingestion → S3 (Parquet) → Glue → Athena → Quick; Lake Formation permissions · Assessed on: Partitioning, cost per query, security"
      },
      {
       "id": "M44.04",
       "title": "Capstone C4: Multi-Region DR",
       "level": "400",
       "concepts": "Warm-standby version of C1 in a second Region with Route 53 failover; a documented DR drill with measured RPO/RTO · Assessed on: Meets the RPO/RTO target, runbook quality"
      },
      {
       "id": "M44.05",
       "title": "Capstone C5: Self-hosted LMS on AWS (optional)",
       "level": "400",
       "concepts": "Deploy this LMS to AWS using the reference architecture in §6.4 · Assessed on: End-to-end architect portfolio piece"
      }
     ]
    },
    {
     "id": "M45",
     "title": "Exam readiness",
     "track": "N",
     "levels": "300",
     "hours": "15 h",
     "exam": "",
     "prereqs": [],
     "lessons": [
      {
       "id": "M45.01",
       "title": "Exam technique",
       "level": "300",
       "concepts": "Time management (about 2 min per question), flagging, elimination, reading constraint keywords"
      },
      {
       "id": "M45.02",
       "title": "Distractor patterns",
       "level": "300",
       "concepts": "Over-engineered answers, \"works but isn't the cheapest\", services that don't exist in that context"
      },
      {
       "id": "M45.03",
       "title": "Mock exams 1–6",
       "level": "300",
       "concepts": "65 questions, 130 minutes, domain-weighted, full explanations"
      },
      {
       "id": "M45.04",
       "title": "Weak-area remediation",
       "level": "300",
       "concepts": "Auto-generated review lessons from the learner's error log"
      },
      {
       "id": "M45.05",
       "title": "Final revision pack",
       "level": "300",
       "concepts": "Decision tables, the 50 most-tested comparisons, flashcard sprint"
      },
      {
       "id": "M45.06",
       "title": "Exam-day logistics",
       "level": "100",
       "concepts": "Online proctoring vs test centre, ID, retake policy"
      }
     ]
    }
   ]
  },
  {
   "id": "O",
   "title": "Elective",
   "modules": [
    {
     "id": "M46",
     "title": "AI agents on AWS (elective)",
     "track": "O",
     "levels": "200–400",
     "hours": "15 h",
     "exam": "none",
     "prereqs": [
      "M16",
      "M25"
     ],
     "lessons": [
      {
       "id": "M46.01",
       "title": "RAG and agents",
       "level": "200",
       "concepts": "LLMs, retrieval-augmented generation (RAG), the agentic stack on AWS"
      },
      {
       "id": "M46.02",
       "title": "Tools and memory",
       "level": "300",
       "concepts": "Tool use, short-term/long-term memory, Bedrock AgentCore Memory"
      },
      {
       "id": "M46.03",
       "title": "Multi-agent patterns",
       "level": "400",
       "concepts": "Orchestration patterns, when multi-agent isn't the answer"
      },
      {
       "id": "M46.04",
       "title": "Protocols",
       "level": "400",
       "concepts": "Model Context Protocol (MCP), Agent2Agent (A2A)"
      },
      {
       "id": "M46.05",
       "title": "Production, evaluation, governance",
       "level": "400",
       "concepts": "AgentCore deployment, evaluations, observability, guardrails"
      }
     ]
    }
   ]
  }
 ]
};
