/* M10 — VPC connectivity and private access. Original teaching scenarios. */
(function () {
  "use strict";
  var lessons = [], flashcards = [];
  var refs = {
    peering: ['VPC peering behavior and limitations', 'https://docs.aws.amazon.com/vpc/latest/peering/vpc-peering-basics.html'],
    tgw: ['Transit Gateway routing', 'https://docs.aws.amazon.com/vpc/latest/tgw/how-transit-gateways-work.html'],
    tables: ['Transit Gateway route tables', 'https://docs.aws.amazon.com/vpc/latest/tgw/tgw-route-tables.html'],
    attachments: ['VPC attachment constraints', 'https://docs.aws.amazon.com/vpc/latest/tgw/tgw-vpc-attachments.html'],
    tgwpeer: ['Transit Gateway peering', 'https://docs.aws.amazon.com/vpc/latest/tgw/tgw-peering.html'],
    gateway: ['Gateway endpoints', 'https://docs.aws.amazon.com/vpc/latest/privatelink/gateway-endpoints.html'],
    s3: ['S3 gateway endpoint routing and policies', 'https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-s3.html'],
    interface: ['AWS services through PrivateLink', 'https://docs.aws.amazon.com/vpc/latest/privatelink/privatelink-access-aws-services.html'],
    policy: ['Endpoint policy evaluation', 'https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-access.html'],
    service: ['Create a PrivateLink endpoint service', 'https://docs.aws.amazon.com/vpc/latest/privatelink/create-endpoint-service.html'],
    egress: ['Centralized IPv4 egress', 'https://docs.aws.amazon.com/whitepapers/latest/building-scalable-secure-multi-vpc-network-infrastructure/using-nat-gateway-for-centralized-egress.html'],
    price: ['VPC pricing', 'https://aws.amazon.com/vpc/pricing/'],
    plprice: ['PrivateLink pricing', 'https://aws.amazon.com/privatelink/pricing/'],
    tgprice: ['Transit Gateway pricing', 'https://aws.amazon.com/transit-gateway/pricing/'],
    lattice: ['VPC Lattice concepts', 'https://docs.aws.amazon.com/vpc-lattice/latest/ug/what-is-vpc-lattice.html'],
    auth: ['VPC Lattice auth policies', 'https://docs.aws.amazon.com/vpc-lattice/latest/ug/auth-policies.html'],
    flowlogs: ['Flow Log fields and interpretation', 'https://docs.aws.amazon.com/vpc/latest/userguide/flow-log-records.html']
  };
  function esc(s) { return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
  function text(x, y, value, cls) { return '<text class="' + (cls || 'dg-t') + '" x="' + x + '" y="' + y + '">' + esc(value) + '</text>'; }
  function box(x, y, w, h, title, detail, cls) {
    return '<rect class="' + (cls || 'dg-box') + '" x="' + x + '" y="' + y + '" width="' + w + '" height="' + h + '" rx="8"/>' +
      text(x + 12, y + 25, title, 'dg-tb') + (detail || []).map(function (s, i) { return text(x + 12, y + 47 + i * 18, s, 'dg-t'); }).join('');
  }
  function edge(id, d, label, x, y, dashed) {
    return '<path class="dg-line" d="' + d + '" marker-end="url(#' + id + '-arrow)"' + (dashed ? ' stroke-dasharray="5 4"' : '') + '/>' + (label ? text(x, y, label, 'dg-ts') : '');
  }
  function fig(id, title, desc, height, draw) {
    return '<figure class="connectivity-figure"><div class="connectivity-diagram-scroll" tabindex="0" role="region" aria-label="' + esc(title + '. Scroll horizontally on a narrow screen.') + '"><svg class="diagram" viewBox="0 0 760 ' + height + '" role="img" aria-labelledby="' + id + '-title ' + id + '-desc"><title id="' + id + '-title">' + esc(title) + '</title><desc id="' + id + '-desc">' + esc(desc) + '</desc><defs><marker id="' + id + '-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path fill="currentColor" d="M0 0 L10 5 L0 10 Z"/></marker></defs>' + draw(id) + '</svg></div><figcaption><strong>' + esc(title) + '.</strong> ' + esc(desc) + '</figcaption></figure>';
  }
  function flow(id, title, desc, steps) {
    return fig(id, title, desc, 250, function (fid) {
      return steps.map(function (s, i) { var x = i % 2 ? 404 : 24, y = i < 2 ? 12 : 146;
        return box(x, y, 330, 84, (i + 1) + '. ' + s[0], [s[1]], i === 3 ? 'dg-good' : 'dg-box');
      }).join('') + edge(fid, 'M354 54 H404', '', 0, 0) + edge(fid, 'M568 96 V121 H190 V146', 'Continue', 360, 116) + edge(fid, 'M354 188 H404', '', 0, 0);
    });
  }
  function q(id, stem, answers, task, level) {
    return { id: id, stem: stem, type: answers.filter(function (a) { return a[1]; }).length > 1 ? 'multi' : 'single', task: task || '3.4', domain: 'D' + (task || '3.4')[0], level: level || 300,
      options: answers.map(function (a) { return { t: a[0], c: a[1], why: a[2] }; }) };
  }
  function add(n, title, level, minutes, objectives, sections, checks, drills, cards, sources) {
    var id = 'M10.0' + n;
    lessons.push({ id: id, title: title, level: level, minutes: minutes, objectives: objectives, sections: sections,
      check: checks.map(function (a, i) { return q(id + '-k' + (i + 1), a[0], a[1], a[2], level); }),
      drills: drills.map(function (a, i) { return { id: id + '-d' + (i + 1), q: a[0], answers: a[1], explain: a[2] }; }),
      cards: cards.map(function (a, i) { var cid = 'fc-' + id + '-' + (i + 1); flashcards.push({ id: cid, front: a[0], back: a[1] }); return cid; }),
      references: sources.map(function (key) { return '<a href="' + refs[key][1] + '">' + refs[key][0] + '</a>'; }) });
  }

  function section(type, html) { return {type: type, html: html}; }
  function steps(items) { return '<ol class="flow">' + items.map(function(s) {return '<li>' + s + '</li>';}).join('') + '</ol>'; }
  function cases(items) { return items.map(function(c) { return '<h3>' + c[0] + '</h3><p>' + c[1] + '</p>'; }).join(''); }
  function architecture(n, title, desc, nodes, links) {
    return fig('m10-arch-' + n, 'Architecture: ' + title, desc, 330, function(id) {
      return nodes.map(function(b, i) {return box(i % 2 ? 404 : 24, i < 2 ? 20 : 200, 330, 100, b[0], b.slice(1), i < 2 ? 'dg-region' : 'dg-info');}).join('') +
        links.map(function(e) {return edge(id,e[0],e[1],e[2],e[3],e[4]);}).join('');
    });
  }
  add(1, 'VPC peering', 200, 40,
    ['Trace a request and reply across a peering connection', 'Reject designs that require transitive or overlapping peering', 'Separate DNS, routing and application authorization'], [
    section('why', `<p>A reporting application in VPC A needs TCP 5432 access to a database in VPC B. Both owners want private connectivity without creating a shared network hub. Start by writing the exact source, destination and port: a requirement to reach one database is different from permission to reach every subnet in its VPC.</p>`),
    section('concept', `<p>VPC peering joins two VPC routing domains through a direct connection. It does not merge their route tables, security groups or account ownership. Think of two buildings installing a private doorway: the doorway exists, but each building still controls which rooms a visitor can reach. The connection can cross accounts and Regions, with each owner responsible for their side.</p><p>For the reporting request, enumerate two independent paths: the route from the reporting subnet toward the database address and the route back toward the reporting address. An active peering connection is only one link in that chain. A stale return route can make a correctly configured client look broken.</p><p>Address uniqueness is a prerequisite. Adding a narrow route cannot fix overlapping VPC CIDRs. Peering is also non-transitive: A–B and B–C do not provide A–C connectivity. A team proposing a shared internet exit in B for A has introduced a different requirement; a peer cannot borrow B’s NAT gateway. Treat DNS resolution as a separate design decision rather than assuming private hosted zones become shared when a connection is accepted.</p>` + architecture(1, 'direct peers retain separate controls', 'A reaches B directly. A cannot reach C through B; a separate A–C connection or a routed hub design is required.',
      [['VPC A — reporting','10.100.0.0/16','Route B CIDR → pcx-ab'],['VPC B — database','10.101.0.0/16','Route A CIDR → pcx-ab'],['VPC C — analytics','10.102.0.0/16','Has a separate B–C peer'],['Boundary rule','A–B plus B–C is not A–C','No shared NAT via peering']],
      [['M354 70 H404','pcx-ab',360,56],['M560 120 V158 H190 V200','B–C only',325,152]])),
    section('aws', `<p>Request, accept, then route: configure each relevant subnet table and permit the application through SGs and NACLs. Same-Region peer security-group references are available; do not assume that support across Regions. The peering DNS option can make a peer’s public EC2 hostname resolve to its private address. Private hosted-zone associations and hybrid DNS forwarding still require their own configuration. Check all primary and secondary CIDRs before requesting the connection.</p>`),
    section('workflow', flow('m10-flow-1','Workflow: diagnose a peer connection','Walk from address ownership to a real application response; the return path is a first-class check.',[
      ['Inventory addresses','Check all VPC CIDRs'],['Activate and route','Accept; configure both sides'],['Permit the flow','SG, NACL, DNS and listener'],['Probe and correlate','Request, reply and timestamp']]) + steps(['Confirm the two VPC owners, Regions and non-overlapping ranges.','Accept the peer; route only required destination ranges from each workload table.','Permit the chosen port and required NACL return ports; inspect actual DNS answers.','Send a bounded application request and inspect the reply, not just the connection status.'])),
    section('examples', `<h3>Trace the database connection</h3><p>Client 10.100.10.20:41000 sends to 10.101.20.30:5432. A’s app table matches 10.101.0.0/16 → pcx-ab. B’s database SG permits TCP 5432 from the approved client range or supported peer SG. The reply targets 10.100.10.20:41000 and uses B’s 10.100.0.0/16 → pcx-ab route. A missing B route is not repaired by widening the database SG.</p><h3>Estimate a mesh</h3><p>Six VPCs needing every pair require 6 × 5 ÷ 2 = 15 peer connections. Twenty need 190. This calculation counts connections, not subnet routes or policy changes; operational work can grow faster than the diagram suggests.</p>`),
    section('usecases', cases([
      ['Two stable application VPCs','Choose a direct peer when the allowed flows and ownership are simple. Keep destination routes narrow. The trade-off is pair-specific administration; loss of the sole logical connection removes this path, so application retry and recovery behavior still matter.'],
      ['Acquisition with duplicate addresses','Both businesses use 10.0.0.0/16. Do not try narrower peer routes. For one published API, assess PrivateLink; for general connectivity, plan renumbering or an explicitly designed translation boundary. The latter adds troubleshooting and audit work.'],
      ['Rapidly growing platform','A request to connect dozens of VPCs changes the operating problem. Compare Transit Gateway segmentation with a peer mesh. A hub simplifies connection management but adds routing policy, cost and a larger shared dependency.'] ])),
    section('demo', `<p>Offline exercise: draw A–B and B–C, then mark A’s route to C as unsupported. Add a direct A–C peer on paper and write both return routes. For an existing sandbox connection, use <code>aws ec2 describe-vpc-peering-connections --region REGION</code> and <code>aws ec2 describe-route-tables --filters Name=vpc-id,Values=VPC_ID --region REGION</code>. These are inventory commands; they do not test an application listener.</p>`),
    section('exam', `<p>Look for a small number of non-overlapping VPCs and direct private connectivity. Reject peering when the decisive requirement is transitive routing, overlapping ranges, or shared NAT access. Cross-account or cross-Region alone does not disqualify peering. Avoid selecting a hub solely because it sounds more sophisticated.</p>`),
    section('architect', `<p>Assign route ownership and change windows on both sides. Model name resolution separately and record the expected resolved address. Do not interpret an active control-plane status as proof of data-plane health. During troubleshooting, freeze unrelated changes so a route repair can be distinguished from an SG repair.</p>`),
    section('summary', `<ul><li>Peering is direct and non-transitive.</li><li>Overlapping CIDRs block the design.</li><li>Request and reply need valid routes.</li><li>DNS and security controls remain independent.</li><li>Mesh administration grows with the number of pairs.</li></ul>`)
  ], [
    ['A peers with B and B peers with C. A must call C. What is missing?', [['A direct A–C peer or another supported routed design',true,'B does not transit peer traffic.'],['A default route through the existing A–B peer',false,'A route does not make peering transitive.'],['A larger B subnet',false,'Subnet capacity is unrelated.'],['Public DNS in B',false,'DNS does not add a supported path.']]],
    ['Only a secondary CIDR overlaps between two proposed peers. What should the team do?', [['Resolve the overlap or choose a suitable service-access design',true,'All VPC CIDRs matter to peering eligibility.'],['Peer only the non-overlapping subnet',false,'Peering is between VPCs.'],['Use TCP instead of UDP',false,'Protocol choice cannot remove overlap.'],['Accept the peer twice',false,'Acceptance cannot override the constraint.']]],
    ['A peer is active but the client times out. Which TWO checks are useful?', [['Inspect the server subnet return route',true,'Responses need a valid path.'],['Verify the target listener and security controls',true,'Routing does not start an application or authorize its packets.'],['Assume active means the application is healthy',false,'Control-plane status is insufficient.'],['Delete all NACL rules',false,'That is uncontrolled and does not diagnose the issue.'],['Change billing tags',false,'Tags do not route packets.']]],
    ['What does the peering DNS-resolution option establish?', [['Supported peer EC2 public hostnames can resolve to private addresses',true,'This is the specific option behavior.'],['Every private hosted zone is automatically shared',false,'Zone association is separate.'],['All application requests are authorized',false,'DNS resolution is not authorization.'],['Internet egress through the peer NAT',false,'Peering cannot provide this edge-to-edge path.']]]
  ], [
    ['How many pairwise peers form a full mesh of 6 VPCs?', ['15'], '6 × 5 / 2 = 15.'],
    ['Is A–B–C peering transitive? Answer yes or no.', ['no'], 'A needs its own supported path to C.'],
    ['A client is 10.100.10.20. Which /16 should B route back to?', ['10.100.0.0/16'], 'The return destination belongs to VPC A.'],
    ['Can matching IPv4 CIDRs be peered? Answer yes or no.', ['no'], 'Overlapping VPC CIDRs prevent peering.']
  ], [
    ['Peering relationship?', 'One-to-one and non-transitive.'],['Does active peering prove HTTP health?', 'No; routes, controls, DNS and runtime can still fail.'],['Peer mesh formula?', 'n(n−1)/2 connections.'],['Overlapping secondary CIDR?', 'Still prevents peering.'],['Can a peer share its NAT via peering?', 'No.'],['Who owns return routing?', 'The destination VPC owner must configure it.'],['Cross-account peering?', 'Supported with owner acceptance and configuration.'],['Does peering share private hosted zones?', 'No; plan DNS associations or forwarding separately.']
  ], ['peering','tgw','attachments']);

  add(2, 'AWS Transit Gateway', 300, 55,
    ['Distinguish attachment association from propagation', 'Trace forward and return TGW route lookups', 'Design explicit network segmentation'], [
    section('why', `<p>A company has production, development and shared-services VPCs. Both application environments need a package repository, but development must not initiate connections into production. The problem is no longer just connecting VPCs: the network team must express who may reach which destinations and verify that a new attachment does not silently broaden access.</p>`),
    section('concept', `<p>A Transit Gateway is a regional routing hub. A VPC attachment supplies a connection into that hub; subnet route tables still decide which packets leave the VPC toward it. Inside the hub, the route table associated with the ingress attachment decides the next attachment. There is a separate decision on the return journey.</p><p>Association and propagation answer different questions. Association chooses the table used by traffic arriving from an attachment. Propagation installs that attachment’s reachable prefixes into selected tables. One attachment associates with one TGW route table at a time, while its routes can propagate into several. Neither operation adds routes to the workload’s VPC tables.</p><p>For the company’s design, associate development with a table containing shared-services destinations but no production destination or broad fallback that reaches it. Shared services needs return routes to each approved caller. This achieves a routing boundary, not application authorization; the repository still needs authentication and scoped access. Treat default association and propagation settings as actual policy choices. An attachment becoming available is not evidence that the intended segmentation exists.</p>` + architecture(2,'ingress determines the TGW lookup','Development and production use separate ingress tables. Shared services can reply through its own table; routes and SGs jointly constrain access.',
      [['Development attachment','Associated: dev-table','Routes: shared CIDR only'],['Production attachment','Associated: prod-table','Routes: shared CIDR only'],['TGW routing boundary','No dev → prod route','Propagation is explicit'],['Shared-services attachment','Associated: shared-table','Return routes to dev + prod']],
      [['M190 120 V200','Ingress',200,165],['M570 120 V160 H330 V200','Ingress',435,155],['M354 250 H404','Shared',358,236]])),
    section('aws', `<p>Select attachment subnets in the Availability Zones that need the TGW path; one subnet per AZ per VPC attachment. Traffic from an AZ without appropriate attachment coverage can fail. Overlapping attached VPC address ranges do not become uniquely routable. Share a TGW across accounts using AWS RAM with explicit ownership and acceptance controls. Inter-Region TGW peering needs static routes toward the peering attachment; it is not automatic propagation of every remote VPC route.</p>`),
    section('workflow', flow('m10-flow-2','Workflow: two routing layers, two directions','A route in the workload table, an ingress TGW table and a complete return path are all required.',[
      ['Source subnet table','Remote CIDR → TGW'],['Ingress TGW table','Destination → attachment'],['Destination workload','Local delivery and controls'],['Return lookups','Reverse both routing layers']]) + steps(['Check the source subnet association and remote-CIDR route.','Find the TGW route table associated with the source attachment; look up the destination.','Check attachment AZ coverage and destination-side local routing, SGs and NACLs.','Repeat from the destination back to the source; do not assume symmetric policy.'])),
    section('examples', `<h3>Three-table segmentation worksheet</h3><table><tr><th>Ingress attachment</th><th>Associated TGW table</th><th>Allowed destinations</th></tr><tr><td>Dev 10.100.0.0/16</td><td>dev-table</td><td>Shared 10.102.0.0/16</td></tr><tr><td>Prod 10.101.0.0/16</td><td>prod-table</td><td>Shared 10.102.0.0/16</td></tr><tr><td>Shared 10.102.0.0/16</td><td>shared-table</td><td>Dev and Prod prefixes</td></tr></table><p>Propagate the shared attachment into dev-table and prod-table. Propagate Dev and Prod into shared-table. Do not propagate Prod into dev-table. A default route to an inspection or egress VPC must also be audited: route omission only isolates traffic if no alternate matching path exists.</p><p>Now remove Dev’s route from shared-table. The initial request can reach the repository, yet the reply cannot return. Repair the return table rather than adding a broader outbound route in Dev.</p>`),
    section('usecases', cases([
      ['Organization with many VPCs','Use RAM to share a centrally managed TGW while VPC owners maintain their workload routes. The advantage is consistent segmentation; the trade-off is a coordination dependency on the network team. Test a new account with both allowed and forbidden flows.'],
      ['Cross-Region shared services','Peer regional TGWs, then explicitly route approved remote prefixes across the peer on both sides. Monitor regional failure and application retry behavior. A peering attachment does not supply automatic full-mesh failover or global service discovery.'],
      ['Acquired network overlaps production','An attachment is not a renumbering tool. Inventory the conflict before enabling propagation. Use service-specific access where appropriate or design a migration; otherwise an ambiguous prefix can break the wrong application during an incident.'] ])),
    section('demo', `<p>Download the <a href="labs/m10/network-plan.json" download>L10 routing worksheet</a> and <a href="labs/m10/check_plan.py" download>offline checker</a>. Run <code>python3 check_plan.py network-plan.json</code>. Remove B’s return route from the TGW table and observe a failed check, then restore it. This models the two-VPC IPv4 lab only; it does not validate AWS, SGs, DNS, RAM permissions or arbitrary enterprise designs.</p>`),
    section('exam', `<p>Many VPCs, centralized routing and transitive connectivity point toward TGW. A single service exposed to overlapping customers points toward PrivateLink instead. For a one-way failure, identify the ingress table for each direction before changing security controls. RAM shares a resource; it does not install every required workload route.</p>`),
    section('architect', `<p>Maintain a connectivity matrix with both permitted and denied probes. Separate deployment rights for attachment creation and route-policy changes. Stateful inspection introduces symmetry requirements and may require appliance mode; adding a firewall to a diagram is not enough. Price attachments and processed traffic as well as the operational benefit of central control.</p>`),
    section('summary', `<ul><li>VPC routes and TGW routes are separate layers.</li><li>Association selects the ingress lookup table.</li><li>Propagation advertises destinations into tables.</li><li>Test return paths and forbidden paths.</li><li>Cross-Region peering requires explicit routing.</li></ul>`)
  ], [
    ['Which table handles a packet entering TGW from Dev?', [['The TGW table associated with the Dev attachment',true,'Ingress association selects the lookup.'],['Every table receiving Dev propagation',false,'Propagation advertises routes, not ingress table selection.'],['The destination account billing table',false,'Billing does not select paths.'],['Always the default table',false,'Explicit associations can replace that choice.']]],
    ['Shared routes propagate into Dev’s table. What is still required in Dev?', [['A workload subnet route toward TGW',true,'TGW propagation does not edit VPC route tables.'],['A public IP on the private server',false,'Private routing does not require a public IP.'],['A new IGW for the TGW link',false,'TGW is not reached through an IGW.'],['An S3 endpoint as a transit router',false,'Gateway endpoints do not route between VPCs.']]],
    ['Which TWO support deliberate TGW segmentation?', [['Explicit attachment-to-table associations',true,'They define each ingress routing view.'],['Auditing propagation and fallback routes',true,'A broad alternate route can defeat isolation.'],['Propagating all prefixes to every table',false,'That tends toward full connectivity.'],['Assuming SGs are copied across attachments',false,'They are not copied.'],['Ignoring the return direction',false,'Replies have their own lookup.']]],
    ['Two TGWs are peered across Regions. How are approved remote prefixes routed across the peer?', [['Configure static routes toward the peering attachment',true,'Do not assume dynamic route propagation across this peer.'],['Enable VPC DNS hostnames only',false,'DNS does not install TGW routes.'],['Share an S3 gateway endpoint',false,'It is not an inter-Region routing hub.'],['Use identical overlapping CIDRs',false,'That creates ambiguity instead of connectivity.']]]
  ], [
    ['What selects the TGW table for incoming attachment traffic: association or propagation?', ['association'], 'Association selects the ingress routing view.'],
    ['Can an attachment propagate into multiple TGW tables? yes/no', ['yes'], 'Propagation and association have different cardinalities.'],
    ['Does TGW propagation add workload VPC routes? yes/no', ['no'], 'Configure VPC route tables independently.'],
    ['Which AWS service shares a TGW between accounts? Use its acronym.', ['ram','aws ram'], 'Resource Access Manager shares the resource.']
  ], [
    ['Association versus propagation?', 'Ingress lookup selection versus route advertisement.'],['TGW attachment associated tables?', 'One at a time.'],['Propagation destinations?', 'An attachment can propagate into multiple tables.'],['Does TGW solve overlapping CIDRs?', 'No; plan unique routed addressing or a service/translation boundary.'],['Cross-account TGW sharing?', 'AWS RAM plus explicit attachment and route management.'],['TGW peer route type?', 'Static routes toward the peering attachment.'],['Why inspect both directions?', 'The reply enters through another attachment and table.'],['Does a route grant app authorization?', 'No; network and application controls are separate.']
  ], ['tgw','tables','attachments','tgwpeer','tgprice']);
  add(3, 'VPC endpoints', 300, 50,
    ['Choose gateway or interface endpoints for a specified client', 'Trace route-based and DNS-based private service access', 'Diagnose authorization separately from connectivity'], [
    section('why', `<p>A private worker downloads objects from S3 and calls a secrets API. Sending both through NAT works, but the team wants a narrower service path and a defensible cost estimate. The right design depends on the service, client location, DNS behavior and traffic volume; “private endpoint” is not one interchangeable product.</p>`),
    section('concept', `<p>A gateway endpoint steers matching service destinations through a route-table entry. An interface endpoint gives a supported service private network interfaces inside selected subnets. The distinction matters when explaining a packet: for the gateway path, inspect the destination prefix and associated route table; for the interface path, inspect DNS, the resolved private address and endpoint security group.</p><p>In an IPv4 S3 gateway example, the hostname can still resolve to public service addresses. That does not prove internet routing: the AWS-managed prefix-list route can select the gateway endpoint instead of a default NAT route. Conversely, merely creating an interface endpoint does not guarantee an application uses it. The application’s resolver and endpoint hostname must lead to the intended ENI.</p><p>Neither path grants permission to read a secret or object. An endpoint policy constrains requests through that endpoint alongside identity, resource and organization policies. Treat access as several independent questions: can the client resolve and reach the destination, is TLS valid, and is the requested action authorized? A timeout and an authenticated AccessDenied response demand different investigations. Keep a known-good small object and caller identity for reproducible tests.</p>` + architecture(3,'route selection versus private ENIs','The S3 gateway path uses a service-prefix route. The interface path uses DNS and endpoint ENIs. Both still require service authorization.',
      [['Private application subnet','S3 service IP → prefix route','Secret API → private DNS'],['S3 gateway endpoint','Associated route tables','No endpoint SG or ENI'],['Interface endpoint ENIs','Private subnet addresses','Endpoint SG permits HTTPS'],['Service authorization','Identity + resource controls','Endpoint policy filters access']],
      [['M354 70 H404','S3',365,55],['M190 120 V200','API',200,165],['M354 250 H404','IAM',365,235],['M568 120 V200','IAM',580,165]])),
    section('aws', `<table><tr><th>Property</th><th>Gateway endpoint</th><th>Interface endpoint</th></tr><tr><td>Mechanism</td><td>Service prefix-list route</td><td>Private ENIs and DNS</td></tr><tr><td>Typical use</td><td>S3 / DynamoDB in the VPC</td><td>Supported AWS or provider services</td></tr><tr><td>Network filter</td><td>Workload SG/NACL; no endpoint SG</td><td>Endpoint SG plus workload controls</td></tr><tr><td>Endpoint charge</td><td>No additional endpoint charge</td><td>Hourly and data-processing dimensions</td></tr></table><p>Gateway endpoints are not PrivateLink. An S3 gateway endpoint cannot be consumed through TGW, peering, VPN or Direct Connect from another network. Interface endpoints can support routed remote clients with suitable routing and DNS. Verify the service’s current IP-family support; gateway endpoints are not universally IPv4-only. The lab deliberately uses IPv4 to keep route evidence unambiguous.</p>`),
    section('workflow', flow('m10-flow-3','Workflow: prove the endpoint path','Resolve first, identify the network target, then evaluate service permissions and the observed response.',[
      ['Resolve service name','Record IP family and address'],['Select the path','Prefix route or endpoint ENI'],['Evaluate controls','SG/NACL and IAM policies'],['Correlate evidence','Request result + routes + logs']]) + steps(['Identify the service, Region and whether the client is local or remote.','Inspect DNS answers from the actual worker, not just the operator laptop.','For S3 gateway access, inspect the worker’s effective route-table association and managed prefix list.','For interface access, inspect endpoint state, ENIs, private DNS and TCP 443 SG rules.','Use the same caller and request when changing one policy or route at a time.'])),
    section('examples', `<h3>Public-looking address, private service route</h3><p>The app table has 0.0.0.0/0 → NAT and an S3 prefix-list route → vpce-s3. The same-Region S3 destination matches the service route, so its traffic avoids the default route. A request to another destination still uses NAT. If only a different subnet’s table is associated with the endpoint, the worker does not benefit.</p><h3>AccessDenied is not a route diagnosis</h3><p>A worker reads lab.txt but is denied private.txt. The endpoint is reachable; compare object ARN scope, caller role, bucket policy, endpoint policy and any explicit deny. Replacing the route cannot grant GetObject. If the object uses SSE-KMS, include the relevant key permissions in the investigation.</p>`),
    section('usecases', cases([
      ['Same-Region S3 batch processing','Use a gateway endpoint associated with each intended worker table. The endpoint itself adds no hourly fee. Preserve a path for other dependencies such as package repositories and administration; removing NAT blindly can strand the worker even while S3 works.'],
      ['On-premises analytics clients','A central S3 gateway endpoint cannot serve these clients through the VPN. Evaluate an S3 interface endpoint with hybrid DNS and routed access. The trade-off is paid endpoint capacity and DNS operation; test name resolution from the actual on-premises resolver.'],
      ['Isolated secret retrieval','Use a supported interface endpoint with private DNS and an endpoint SG scoped to callers. An endpoint in one AZ creates a zonal dependency for that placement. Compare multiple-AZ placement, client retry behavior and cost against the availability requirement.'] ])),
    section('demo', `<p>In L10, use <code>aws ec2 describe-vpc-endpoints --region REGION --filters Name=vpc-id,Values=VPC_ID</code> and inspect the worker subnet’s effective route table. For a gateway endpoint, list its route-table associations. For an interface endpoint, inspect NetworkInterfaceIds and PrivateDnsEnabled. Do not print temporary credentials or signed URLs into shared evidence. The runbook uses a small non-sensitive object.</p>`),
    section('exam', `<p>“Same-Region S3 from a VPC, lowest endpoint cost” suggests a gateway endpoint. “Private AWS API ENIs” suggests an interface endpoint. “On-premises S3 through private connectivity” rules out simply borrowing a gateway endpoint. Endpoint policy is an additional access boundary, not a replacement for required IAM permission.</p>`),
    section('architect', `<p>Use separate names for network reachability tests and authorization tests in the evidence log. Restrictive endpoint policies can break supporting service downloads. S3 source-endpoint conditions can also deny console or recovery access; limit the lab condition to a disposable object read and keep the administrative path independent. Existing connections can break when routes switch, so reconnect for each trial.</p>`),
    section('summary', `<ul><li>Gateway: service prefix routing.</li><li>Interface: private ENIs, DNS and SGs.</li><li>Check the actual subnet association.</li><li>Remote clients cannot borrow S3 gateway access.</li><li>Reachability and permission require separate evidence.</li></ul>`)
  ], [
    ['A worker needs same-Region S3 with no endpoint hourly charge. Which fits?', [['S3 gateway endpoint associated with the worker route table',true,'This is the route-based local service path.'],['A paid interface endpoint as the only option',false,'Local S3 has a gateway alternative.'],['An IGW without public addressing',false,'That does not provide this private endpoint path.'],['TGW peering to S3',false,'S3 is not attached as a peer VPC.']]],
    ['A secrets interface endpoint exists, but the app resolves the public API address. What should be checked?', [['Private DNS settings and the app’s resolver path',true,'Creation alone does not redirect every resolver.'],['Only the S3 prefix list',false,'That does not control the secrets hostname.'],['Whether all buckets are public',false,'Unrelated and unsafe.'],['The TGW attachment name',false,'Names do not resolve service APIs.']]],
    ['Which TWO statements about endpoint policies are correct?', [['They constrain requests using the endpoint',true,'They are an additional policy boundary.'],['They do not replace required IAM permissions',true,'Other policy evaluations still apply.'],['They force every caller to use that endpoint',false,'Other paths need their own controls.'],['They open TCP 443 in the endpoint SG',false,'Network SG rules are separate.'],['They remove explicit organization denies',false,'An allow does not override an applicable explicit deny.']]],
    ['An S3 hostname resolves to public IPv4 addresses. Does that prove the worker uses NAT?', [['No; inspect prefix-list routing in the effective subnet table',true,'Gateway routing can use those service addresses.'],['Yes, public-looking DNS always means NAT',false,'DNS addresses do not identify the selected route.'],['No, because every S3 address is an ENI in the VPC',false,'Gateway endpoints do not create these ENIs.'],['Yes, unless the bucket is public',false,'Bucket authorization is a separate question.']]]
  ], [
    ['Which endpoint type uses private ENIs: gateway or interface?', ['interface'], 'Interface endpoints provide ENIs in selected subnets.'],
    ['Can B use A’s S3 gateway endpoint through TGW? yes/no', ['no'], 'Gateway access is local to its VPC.'],
    ['Does an endpoint policy grant missing role permissions? yes/no', ['no'], 'It is an additional boundary.'],
    ['Which route is preferred for matching S3 traffic: service prefix or 0.0.0.0/0?', ['service prefix','prefix','service prefix route'], 'The more specific matching service destination wins over the default.']
  ], [
    ['Gateway endpoint services?', 'S3 and DynamoDB; check current service/IP-family support.'],['Gateway endpoint fee?', 'No additional endpoint charge; other service usage still costs.'],['Interface endpoint network object?', 'Private ENIs in selected subnets.'],['Interface endpoint protection?', 'Endpoint SG, workload controls and service policies.'],['Can gateway endpoints transit TGW?', 'No.'],['Is public S3 DNS proof of NAT?', 'No; inspect destination routing.'],['Endpoint policy role?', 'Constrain requests through the endpoint alongside IAM/resource controls.'],['Timeout versus AccessDenied?', 'Investigate path/listener for timeout; inspect authorization for a valid service denial.']
  ], ['gateway','s3','interface','policy','plprice']);

  add(4, 'AWS PrivateLink', 300, 45,
    ['Design an NLB-backed provider service', 'Explain why overlapping consumer addresses can work', 'Separate endpoint acceptance from tenant authentication'], [
    section('why', `<p>A payroll vendor must serve customers that independently use 10.0.0.0/16. Customers want private API access, but neither party wants broad routing into the other’s network. The useful requirement is access to one published service, not joining all customer networks into a common address domain.</p>`),
    section('concept', `<p>In the NLB-backed endpoint-service pattern, the provider publishes a service and the consumer creates an interface endpoint in its own VPC. The consumer connects to local endpoint addresses; PrivateLink carries those connections to the provider’s Network Load Balancer and targets. The two organizations do not exchange routes for their entire CIDR ranges.</p><p>This explains the overlapping-address advantage. A client need not directly address a server at an ambiguous remote 10.0.1.20; it addresses an endpoint ENI in its own network. It also explains the limitation: the provider cannot use this relationship as an unrestricted channel to initiate arbitrary connections back into customer subnets. Responses to consumer-initiated connections are part of the service flow.</p><p>Network exposure and tenant authorization remain separate. A principal allowed to request an endpoint connection has not automatically acquired permission to run payroll for another customer. Bind application credentials to tenants, validate TLS names and log request identities. Build an onboarding checklist that covers allowed principals, acceptance, endpoint availability, DNS and target health so each failure has a distinct owner.</p>` + architecture(4,'publish one service across overlapping VPCs','Consumer and provider may both use 10.0.0.0/16. The consumer connects to its own endpoint ENI, not a directly routed provider IP.',
      [['Consumer VPC — 10.0/16','Client → local endpoint ENI','Consumer SG and DNS'],['PrivateLink boundary','Allowed principal + acceptance','Consumer-initiated connection'],['Provider VPC — 10.0/16','NLB listener → target group','Service and target health'],['Application boundary','TLS and tenant credentials','No full-network route exchange']],
      [['M354 70 H404','Connect',356,55],['M565 120 V157 H190 V200','PrivateLink',320,151],['M354 250 H404','Request',357,235]])),
    section('aws', `<p>For this pattern, create an NLB, listener and healthy target group, then publish an endpoint service. Authorize intended principals and decide whether requests require acceptance. Consumers select supported AZs for interface endpoints. Compare AZ IDs across accounts, because AZ names can map differently. Private DNS names require the provider’s verification and appropriate consumer configuration. Cross-Region PrivateLink is supported when the provider enables it and permissions/Region support align; do not assume the feature is universally same-Region-only.</p>`),
    section('workflow', flow('m10-flow-4','Workflow: onboard a private API consumer','Publish, authorize, connect and authenticate are separate stages, each with its own evidence.',[
      ['Provider publishes','NLB targets and listener healthy'],['Approve consumer','Principal and acceptance rules'],['Consumer connects','Endpoint, SG and DNS ready'],['API authenticates','TLS, tenant and request logs']]) + steps(['Validate target health before diagnosing consumer networking.','Check the permitted principal and endpoint connection state.','Resolve the endpoint name and allow the required listener port from the client.','Call a non-sensitive health/API endpoint, then test authorized and unauthorized tenant requests.'])),
    section('examples', `<h3>Duplicate CIDRs without routed ambiguity</h3><p>Customer A’s client is 10.0.1.10 and its endpoint is 10.0.2.25. The provider also uses 10.0.0.0/16. The client’s destination is the local 10.0.2.25 endpoint, not the provider target. No 10.0.0.0/16 remote route is installed. Publishing only a TCP 443 API does not expose a provider database listener on TCP 5432.</p><h3>Accepted endpoint, failing API</h3><p>The connection is accepted and TCP opens, but the API returns 401. Inspect tenant credentials and token audience. If targets are unhealthy and connections fail earlier, inspect health-check ports, target SGs and application readiness instead. Acceptance is a control-plane event, not an end-to-end health test.</p>`),
    section('usecases', cases([
      ['Multi-tenant SaaS','Publish a private API without requiring customer renumbering. Charge and monitor endpoint usage appropriately. Keep tenant authorization in the application; shared private transport must not imply shared data permissions.'],
      ['Internal service across business units','An internal provider can expose one service to separate accounts. The trade-off is endpoint lifecycle and DNS management per consumer. Test removal of an approved consumer and confirm that the desired access revocation actually takes effect.'],
      ['Request for full bidirectional networking','If the requirement is arbitrary host-to-host traffic across many subnets, this NLB endpoint-service pattern is too narrow. Evaluate routed connectivity with unique addressing. Choose based on the traffic contract instead of trying to turn a service endpoint into a general router.'] ])),
    section('demo', `<p>Offline design exercise: define a payroll service contract with listener TCP 443, a health-check path, approved consumer account, two AZ IDs, DNS name and tenant credential scope. Walk through four faults: pending acceptance, endpoint SG deny, unhealthy target and invalid token. For each, name the responsible owner and the observation that distinguishes it from the others. No NLB or paid endpoint is provisioned by this exercise.</p>`),
    section('exam', `<p>Private service consumption plus overlapping customer CIDRs is a strong PrivateLink signal. The NLB-backed endpoint-service pattern is the focus here; PrivateLink also has other access patterns, so avoid claiming every possible PrivateLink use requires an NLB. Peering and TGW solve broader routing requirements with different address constraints.</p>`),
    section('architect', `<p>Plan multi-AZ provider targets and consumer endpoints, then test a target or AZ failure. Provider applications do not simply receive the original client IP as if this were direct peering; supported proxy-protocol metadata needs explicit configuration and application parsing. Use authenticated tenant identity as the authorization basis. Cross-zone and cross-Region paths can change both failure dependencies and charges.</p>`),
    section('summary', `<ul><li>Publish a service, not an entire network.</li><li>Consumers connect through local endpoint ENIs.</li><li>Overlapping VPC ranges can work for this pattern.</li><li>Acceptance and API authentication are different.</li><li>Test DNS, target health and tenant isolation independently.</li></ul>`)
  ], [
    ['Customers and provider have overlapping CIDRs and need only a private HTTPS API. Which design fits?', [['NLB-backed endpoint service with consumer interface endpoints',true,'The service boundary avoids full CIDR route exchange.'],['A peering mesh using overlapping prefixes',false,'Peering rejects overlap.'],['A public bucket for API credentials',false,'This does not satisfy the private API requirement.'],['A shared gateway endpoint for arbitrary TCP',false,'Gateway endpoints are service-specific, not generic TCP publishers.']]],
    ['An endpoint is accepted but the API returns 401. Where is the strongest next lead?', [['Application credential and tenant validation',true,'The service responded with an authentication failure.'],['Replace every VPC CIDR immediately',false,'Overlap can work in this pattern and does not explain 401.'],['Add an internet gateway',false,'The private API already responded.'],['Disable TLS verification permanently',false,'That undermines identity checks and does not fix authorization.']]],
    ['Which TWO belong in a cross-account PrivateLink onboarding checklist?', [['Supported AZ IDs and endpoint placement',true,'AZ names are account-relative.'],['Allowed principals and acceptance status',true,'They govern endpoint connection setup.'],['Automatic full bidirectional subnet routing',false,'This service pattern does not provide that.'],['Trust any caller because transport is private',false,'Application authentication remains necessary.'],['Assume all targets are healthy after acceptance',false,'Acceptance does not test target health.']]],
    ['The provider wants to initiate arbitrary new connections into customer subnets. Does this endpoint-service relationship supply that?', [['No; it exposes the consumer-initiated service flow',true,'A separate supported design is needed for the new requirement.'],['Yes, every accepted endpoint is a TGW attachment',false,'They are different resources.'],['Yes, if both networks overlap',false,'Overlap does not grant reverse general access.'],['Only if the consumer makes its bucket public',false,'Bucket permissions are unrelated.']]]
  ], [
    ['In the taught endpoint-service pattern, which load balancer is used? Acronym.', ['nlb'], 'A Network Load Balancer fronts the provider targets.'],
    ['Can the taught PrivateLink pattern support overlapping VPC CIDRs? yes/no', ['yes'], 'The consumer addresses its own endpoint ENI.'],
    ['Across accounts compare AZ names or AZ IDs?', ['az ids','ids'], 'AZ IDs identify the same physical Availability Zones.'],
    ['Does endpoint acceptance replace tenant authentication? yes/no', ['no'], 'Transport onboarding is not business authorization.']
  ], [
    ['PrivateLink service boundary?', 'Consumer access to a published service without full-network route exchange.'],['Overlapping ranges?', 'Supported for the described NLB endpoint-service pattern.'],['Consumer-side object?', 'Interface endpoint with private ENIs.'],['Provider-side objects?', 'Endpoint service, NLB, listener and healthy targets.'],['Acceptance proves API health?', 'No.'],['Tenant identity source?', 'Application authentication and authorization, not private transport alone.'],['Cross-account AZ comparison?', 'Use AZ IDs.'],['Cross-Region PrivateLink?', 'Supported with provider enablement, permissions and applicable service/Region support.']
  ], ['service','interface','plprice']);
  add(5, 'Network cost optimisation', 300, 40,
    ['Calculate path cost using explicit assumptions', 'Compare distributed and centralized egress', 'Preserve availability while reducing avoidable processing'], [
    section('why', `<p>A team sees a growing NAT bill and proposes one central gateway for every application. Before approving the change, identify the bytes, destinations and availability requirements. Removing hourly resources can introduce processing fees, cross-zone paths and shared failure dependencies that exceed the savings.</p>`),
    section('concept', `<p>Network cost belongs to a path, not a service name. Sketch the request and response and label every billable hop. For a private worker downloading an object, possible dimensions include NAT processing, NAT hours, public IPv4 allocation, inter-AZ transfer, service requests and storage. A central TGW design adds attachment and processing dimensions. Which of these actually applies depends on the specific service path and pricing rules.</p><p>Separate fixed and variable costs. An hourly endpoint can be expensive for a nearly idle service yet useful at sustained volume. A gateway endpoint can remove NAT processing for eligible local S3 traffic without replacing all internet dependencies. Cost analysis should distinguish removable spend from sunk spend: if NAT must remain for other destinations, adding an interface endpoint may not remove its hourly cost.</p><p>Availability is a constraint on the calculation. A proposal that saves one gateway but makes an application depend on a single AZ is a different product. Compare designs that meet the same recovery and throughput requirements, include observability costs, and record what happens during failover. Use estimated traffic first, then validate the model against measured usage and the bill after charges arrive.</p>` + architecture(5,'cost the complete route','Compare a local S3 gateway path against general egress via a shared hub. Every added hop needs cost and failure analysis.',
      [['Worker VPC','Classify bytes by destination','Measure request + response'],['Local S3 gateway path','Service-prefix route','No gateway endpoint fee'],['Central egress path','TGW → egress VPC → NAT','Attachment + processing + NAT'],['Decision record','Availability + observed volume','Rates, assumptions, owner']],
      [['M354 70 H404','S3',365,55],['M190 120 V200','Other',200,165],['M354 250 H404','Compare',355,235],['M568 120 V200','Compare',578,165]])),
    section('aws', `<p>Use current Region-specific pricing for NAT, TGW and PrivateLink; do not apply one universal cross-AZ fee to every service. Account for per-AZ endpoint placement, endpoint data processing, public IPv4 charges and eligible transfer charges. Centralized egress can reduce gateway count but adds TGW and operational costs. A local gateway endpoint keeps eligible S3 traffic away from that central processing chain. Data transfer pricing has path-specific exceptions, so verify each edge instead of multiplying a remembered flat rate.</p>`),
    section('workflow', flow('m10-flow-5','Workflow: estimate, constrain, measure','A defensible estimate lists rates and assumptions, preserves the SLO and checks actual usage after the change.',[
      ['Inventory traffic','GB, destination, AZ, direction'],['Model each route','Hourly + per-GB components'],['Check constraints','Failure path and service access'],['Verify observed spend','Usage reports and comparison']]) + steps(['Group measured bytes by service, Region, AZ and direction.','Document fixed costs that can actually be removed versus those that remain.','Compute a base and high-volume case using dated pricing inputs.','Review an AZ failure and emergency rollback before changing production routes.','Compare billed usage with the model and explain differences, including logging and storage.'])),
    section('examples', `<h3>Illustrative break-even calculation</h3><p>These are invented teaching rates, not AWS price quotes. Suppose NAT processing is $0.05/GB and a two-AZ interface endpoint costs $0.01 per AZ-hour plus $0.01/GB. NAT remains for other traffic. Over 720 hours, incremental endpoint cost is 2 × 720 × $0.01 + V × $0.01 = $14.40 + $0.01V. Avoided NAT processing is $0.05V. Break-even: $14.40 ÷ ($0.05 − $0.01) = 360 GB. Below that volume, this simplified incremental comparison favors retaining the existing NAT path; above it, the endpoint wins under these assumptions.</p><p>At 1,000 GB, the modeled saving is $50 − ($14.40 + $10) = $25.60. Excluded transfer costs or extra endpoints can change the result. If the service is eligible for a local S3 gateway endpoint, use that separate model rather than paying interface hours by default.</p>`),
    section('usecases', cases([
      ['Large local S3 exports','Associate a gateway endpoint with each relevant worker table and measure NAT processed-byte reduction. Preserve the original workload and object volume during comparison. A lower NAT bill is supporting cost evidence, not proof of every request path.'],
      ['Many lightly used VPCs','Central egress may reduce idle gateway hours. Include TGW processing, attachments, failure paths and operations. A failed central route or firewall policy can affect many teams, so compare the financial saving with the required recovery controls.'],
      ['High-volume cross-zone calls','Move or distribute the appropriate endpoint/service capacity when that preserves resilience. Do not pin all traffic to one AZ just to remove a fee. Verify service-specific transfer treatment and test failover routing under the same cost model.'] ])),
    section('demo', `<p>Create a spreadsheet with columns: path, hours, AZ count, GB by direction, per-unit rate, rate date, fixed costs removed, and failure behavior. Reproduce the 360 GB break-even, then change traffic to 100 GB and 1,000 GB. Finally add a hypothetical $20 monthly DNS cost: the threshold becomes $34.40 / $0.04 = 860 GB. The exercise shows why omitted dependencies can reverse a decision.</p>`),
    section('exam', `<p>First eliminate designs that fail security or availability constraints. Then compare the remaining cost dimensions. “Least expensive” does not always mean fewest gateways. Same-Region S3 traffic unnecessarily processed by NAT is a useful optimization clue. “Centralized” alone is neither a cost guarantee nor an availability guarantee.</p>`),
    section('architect', `<p>Tag cost ownership by workload and network service, but remember that tags alone do not explain packet paths. Capture the before/after volume so a drop in demand is not credited to the architecture change. Budget alarms are delayed notifications, not spending caps. Keep a dated estimate and revisit it when service pricing, traffic or availability requirements change.</p>`),
    section('summary', `<ul><li>Price paths, including replies and dependencies.</li><li>Separate fixed from variable and removable costs.</li><li>Use dated regional rates.</li><li>Compare designs meeting the same availability target.</li><li>Validate estimates with measured usage.</li></ul>`)
  ], [
    ['NAT stays for other services. What should an added interface endpoint be compared against?', [['Its incremental hours and processing versus avoidable NAT processing and transfer',true,'Existing NAT hours are not automatically removed.'],['The entire NAT bill as guaranteed savings',false,'NAT remains deployed.'],['Only endpoint GB charges',false,'Hourly endpoint charges matter.'],['Only the number of icons on the diagram',false,'Diagram size is not a bill.']],'4.4'],
    ['At fictional rates, endpoint fixed cost is $14.40 and per-GB saving is $0.04. Break-even?', [['360 GB',true,'14.40 / 0.04 = 360.'],['36 GB',false,'This is a factor-of-ten error.'],['1,440 GB',false,'The denominator must be the difference in per-GB costs.'],['No break-even can ever exist',false,'The stated assumptions give a positive threshold.']],'4.4'],
    ['Which TWO belong in a central-egress comparison?', [['TGW attachment and processing costs',true,'They are added path dimensions.'],['AZ failure behavior and recovery requirements',true,'Cost options must satisfy the same availability constraint.'],['Assume gateway count determines total cost',false,'Processing and transfer can dominate.'],['Treat budget alerts as a hard cap',false,'They do not cap spend.'],['Ignore return traffic',false,'Replies can dominate byte volume.']],'4.4'],
    ['NAT bytes fell after adding an S3 gateway endpoint, but workload volume also fell. What follows?', [['Normalize for traffic volume and inspect route/request evidence',true,'Both changes could explain the drop.'],['Claim the whole reduction as architectural savings',false,'That ignores the demand change.'],['Delete all monitoring to save more',false,'That removes useful evidence.'],['Assume S3 requests are now free',false,'Endpoint pricing does not remove S3 charges.']],'4.4']
  ], [
    ['Compute 14.40 / 0.04. Enter GB as a number.', ['360'], 'The break-even volume is 360 GB.'],
    ['Under the lesson’s invented rates, savings at 1000 GB? Dollars as a number.', ['25.6','25.60'], '50 − 14.40 − 10 = 25.60.'],
    ['Do budget alerts enforce a spending cap? yes/no', ['no'], 'They notify and can be delayed.'],
    ['Can local eligible S3 gateway traffic avoid NAT processing? yes/no', ['yes'], 'Correct route-table association bypasses the default NAT path.']
  ], [
    ['Cost model unit?', 'An end-to-end traffic path with fixed and variable components.'],['Sunk NAT hours?', 'Not saved if NAT remains required.'],['Break-even formula?', 'Added fixed cost / per-unit variable saving, when saving is positive.'],['Central egress always cheaper?', 'No; include TGW, transfer, availability and operations.'],['Budget alert guarantee?', 'Notification, not a spending cap.'],['Why measure replies?', 'Response bytes may dominate processing and transfer.'],['Gateway endpoint eliminates S3 billing?', 'No; it removes additional endpoint fees and eligible NAT processing, not S3 usage.'],['Rate assumptions?', 'Record Region, date, service path, volume and exclusions.']
  ], ['price','plprice','tgprice','egress']);

  add(6, 'VPC Lattice (awareness)', 400, 40,
    ['Distinguish application connectivity from IP transit', 'Describe services, service networks and access controls', 'Diagnose discovery, authorization and target health separately'], [
    section('why', `<p>Payments, orders and customer services live in different accounts and run on different compute platforms. Each team currently implements its own discovery, connection policy and traffic visibility. The platform team wants a common service-access layer while retaining application ownership. This lesson is architecture enrichment beyond the module’s core exam decisions.</p>`),
    section('concept', `<p>VPC Lattice provides managed application networking across supported resources. In the service-based model, a service represents an application entry point with listeners, rules and target groups. A service network groups services and access relationships. Client connectivity and authorization are then configured around these named services rather than a manual full mesh of every workload subnet.</p><p>Imagine orders calling payments. The architecture review should name the caller, requested operation, service endpoint, forwarding rule and target health signal. An IP route alone cannot describe whether orders may invoke a refund operation. Lattice auth policies can contribute identity-aware controls for supported service requests, while the application still enforces business rules such as which order may be refunded.</p><p>Do not flatten all Lattice features into one model. Current Lattice also includes resource-oriented access, with different objects and policy behavior. This awareness lesson concentrates on service networks and services and flags the boundary: service-network auth policies do not apply to resource configurations. Before choosing the platform for a database, protocol or streaming requirement, verify the exact access model and supported behavior. Product scope changes are a reason to consult current documentation, not to infer support from the name.</p>` + architecture(6,'service access has several policy boundaries','An orders client reaches a named payments service through a service network. Auth policy and forwarding select permitted requests; the application still owns business authorization.',
      [['Orders client VPC','Supported network association','Caller identity and DNS'],['Lattice service network','Service membership and access','AWS_IAM when configured'],['Payments service','Listener → rule → target group','Target health and telemetry'],['Payments application','Business authorization','Request outcome and audit']],
      [['M354 70 H404','Invoke',360,55],['M565 120 V155 H190 V200','Forward',330,150],['M354 250 H404','Request',357,235]])),
    section('aws', `<p>Configure service and service-network associations, supported targets, listener/rule behavior and network access. For services using AWS_IAM authentication, clients must sign supported requests with SigV4/SigV4A as applicable and policy evaluation must allow them. Choosing NONE does not automatically authenticate callers. Use auth policies at the appropriate service/service-network scope, with IAM identity policies as applicable. Resource configurations follow different rules; a service-network auth policy is not a universal firewall for every Lattice resource.</p>`),
    section('workflow', flow('m10-flow-6','Workflow: trace a service invocation','Resolve the intended service, establish network access, evaluate identity, then observe target and application behavior.',[
      ['Discover service','Name and association'],['Establish access','Network controls and transport'],['Authorize invocation','Auth mode, signature, policies'],['Forward and observe','Rule, target health, app result']]) + steps(['Confirm that the chosen Lattice access model supports the application protocol and target.','Verify client/service associations and actual DNS resolution.','Check auth mode, signed caller identity and applicable policies.','Inspect listener/rule selection and target health before attributing failures to IAM.','Correlate access logs and application logs using timestamps and request context.'])),
    section('examples', `<h3>Orders can charge but cannot administer</h3><p>Define the intended caller role and service request scope. Test an authorized invocation with a correctly signed client, then a disallowed caller. Separately test an authenticated request for another customer’s order: the application must reject it even if network-level invocation was permitted.</p><h3>Healthy network, unhealthy target</h3><p>After a deployment, the service name resolves and requests reach the service, but forwarding fails. Check target registration, health checks and readiness. Broadening IAM policies does not start a stopped application. Conversely, a signature error should not be treated as evidence that the route is missing.</p>`),
    section('usecases', cases([
      ['Multiple teams sharing service discovery','Evaluate Lattice when teams need consistent service access and observability across VPC/account boundaries. The benefit is managed application networking; the trade-off is adopting its access model, supported protocols and pricing. Pilot one non-critical service first.'],
      ['Legacy full-network routing','If the task is generic IP transit to arbitrary hosts, assess peering or TGW. Adding Lattice does not erase those routing requirements. Separate the application service contract from infrastructure operations such as backup and administration.'],
      ['Resource-oriented private access','When the requirement names a database or resource configuration, verify the current resource-access documentation and controls. Do not copy a service-network auth policy and assume it protects resource configurations. Assign a specific owner to test the selected model’s positive and negative access cases.'] ])),
    section('demo', `<p>Write a service contract for orders → payments with caller role, service name, allowed operation, target type, auth mode, timeout, retry limit and audit fields. Classify four faults: wrong DNS name, unsigned request under AWS_IAM, unhealthy target and rejected business operation. This is an offline architecture exercise; it does not create paid Lattice resources.</p>`),
    section('exam', `<p>Keep Lattice as awareness-level enrichment rather than a claim that the exam requires every feature. For core scenarios, continue to distinguish direct VPC peering, TGW transit, gateway/interface endpoints and PrivateLink service exposure. Select application networking only when the requirements actually call for its service model.</p>`),
    section('architect', `<p>Document which layer retries and enforce a retry budget so platform and application retries do not multiply overload. Test an unauthorized caller and an unhealthy target separately. An access log confirms an observed request outcome; it does not establish that every business-level operation is safe. Revisit protocol support, auth behavior and resource-access differences before expanding the deployment.</p>`),
    section('summary', `<ul><li>Lattice adds managed application connectivity.</li><li>Services use listeners, rules and targets.</li><li>Service networks group access relationships.</li><li>AWS_IAM requires appropriate signed requests and policies.</li><li>Resource configurations have distinct policy behavior.</li><li>Business authorization stays with the application.</li></ul>`)
  ], [
    ['A team needs common service access across application VPCs. Which option merits evaluation?', [['VPC Lattice with supported services and an explicit access model',true,'It addresses managed application networking.'],['A larger subnet mask as service discovery',false,'Address sizing does not provide service policy.'],['An S3 gateway endpoint for all HTTP applications',false,'It is service-specific.'],['An IGW as tenant authentication',false,'Internet routing is not identity control.']]],
    ['A Lattice service uses AWS_IAM. An unsigned request fails. What should be checked?', [['Supported request signing and applicable identity/auth policies',true,'Transport reachability is not sufficient.'],['Only the number of NAT gateways',false,'That does not fix request authentication.'],['Whether every private subnet is public',false,'Public exposure is not required.'],['The S3 object lifecycle rule',false,'Unrelated to this request.']],'1.2'],
    ['Which TWO are separate from successful Lattice network access?', [['Target health and application readiness',true,'A reachable service can have unhealthy targets.'],['Business authorization for the requested operation',true,'Allowed invocation does not authorize every business action.'],['Automatic permission to refund all customers',false,'That must not follow from transport access.'],['Guaranteed support for every protocol',false,'Verify the selected model.'],['Automatic protection of resource configurations by service-network auth policy',false,'That policy does not apply to resource configurations.']],'1.2'],
    ['Why verify whether a design uses a Lattice service or resource configuration?', [['Their objects and applicable authorization behavior differ',true,'Do not apply service-policy assumptions universally.'],['They are always identical names for the same object',false,'The distinction affects configuration and controls.'],['Neither can have any access constraints',false,'They have applicable controls.'],['Only spelling affects billing',false,'Behavior and access model matter.']]]
  ], [
    ['Lattice AWS_IAM requests need signing: yes/no?', ['yes'], 'Use the supported signing and authorization model.'],
    ['Do service-network auth policies apply to resource configurations? yes/no', ['no'], 'Verify the separate resource-access controls.'],
    ['Does a healthy network prove healthy application targets? yes/no', ['no'], 'Health and runtime require separate evidence.'],
    ['Is this Lattice lesson core coverage or awareness enrichment? Enter awareness or core.', ['awareness'], 'The curriculum labels it beyond-exam enrichment.']
  ], [
    ['Lattice service components?', 'Listeners, routing rules and target groups around an application entry point.'],['Service network purpose?', 'Group services and access relationships.'],['AWS_IAM auth mode?', 'Use supported signed requests and applicable policies.'],['NONE auth mode?', 'Does not establish IAM authentication by itself.'],['Resource configurations caveat?', 'Service-network auth policies do not apply to them.'],['Lattice equals generic IP transit?', 'No; choose the supported application/resource access model.'],['Target failure versus signature failure?', 'Check runtime/health versus request identity and signing separately.'],['Who owns business authorization?', 'The application, even when network invocation is authorized.']
  ], ['lattice','auth','service']);
  // Independent scenario quiz: not a replay of lesson-check stems.
  var quizRows = [
    ['Two non-overlapping VPCs have stable, bidirectional private database traffic and need no transit. Which is the simplest candidate?', 'Direct VPC peering with explicit routes and controls', 'It meets the limited pairwise requirement.', ['A mandatory TGW for every two-VPC design','TGW is an option, not required for this simple pair.'], ['An S3 gateway endpoint','It cannot publish a database listener.'], ['A public database as the only solution','Private connectivity is available.']],
    ['A server receives requests over a peer, but replies follow the wrong destination route. What should be repaired first?', 'The server subnet’s effective return route', 'The stated evidence identifies the reply path.', ['The client’s DNS TTL only','DNS TTL does not fix an already identified return route.'], ['The server’s billing tag','Tags do not forward replies.'], ['A larger internet gateway','This is private peer routing.']],
    ['A proposed hub VPC would let its peers use its NAT. Which review finding is decisive?', 'Peering does not support that shared NAT path', 'A different supported egress architecture is needed.', ['Peers must always be in the same account','Cross-account peers are supported.'], ['Every peer must have identical CIDRs','Identical CIDRs prevent peering.'], ['Peering requires public IPs on clients','Private addresses can be used.']],
    ['Eight VPCs require a full peer mesh. How many connections must be managed?', '28', '8 × 7 / 2 = 28.', ['8','That does not connect every pair.'], ['56','That double-counts each pair.'], ['7','That is a spanning tree, which does not supply transitive peering.']],
    ['Dev must reach Shared but never Prod. Which TGW policy is a sound starting point?', 'Associate Dev with a table containing Shared and no route or fallback to Prod', 'Then validate both allowed and forbidden traffic and retain security controls.', ['Propagate all attachments into Dev’s table','That advertises Prod as reachable.'], ['Rely only on attachment names','Names do not restrict routing.'], ['Remove Shared’s return route to Dev','That breaks the required allowed flow.']],
    ['A VPC has workloads in two AZs but its TGW attachment covers only one. A route exists in both workload tables. What warrants inspection?', 'Attachment subnet coverage for the failing AZ', 'Route entries alone do not provide attachment presence in each required AZ.', ['S3 bucket versioning','It does not determine TGW connectivity.'], ['Whether the instance hostname contains the AZ name','Naming does not provide coverage.'], ['The number of flashcards completed','LMS progress cannot configure AWS.']],
    ['The TGW table has the remote prefix, but the worker table has no TGW route. What follows?', 'Add the intended remote route to the correct workload table', 'TGW propagation does not install it there.', ['Wait for propagation to rewrite every VPC table','Those tables are managed separately.'], ['Make the S3 bucket public','Unrelated to routed VPC traffic.'], ['Change only the TGW Name tag','Tags do not install routes.']],
    ['A network owner shares TGW through RAM. Which task still belongs in onboarding?', 'Verify attachment state, table association and both VPC-side routes', 'Resource sharing is only part of the complete connection.', ['Assume every participant automatically has full reachability','Sharing does not create all routes and policies.'], ['Replace all private addresses with public ones','Not required for TGW.'], ['Remove all return routes for isolation','That breaks authorized replies too.']],
    ['Only workers in subnet X still use NAT for S3 after a gateway endpoint is added. What is the best lead?', 'X’s effective route table may not be associated with the endpoint', 'Association determines where the service route is installed.', ['S3 gateway endpoints require an endpoint SG','They do not have endpoint ENI security groups.'], ['Every worker requires a new public IP','Gateway access does not require it.'], ['NAT must always override more-specific S3 routes','The default route does not have that priority.']],
    ['A caller reaches an interface ENI but TLS/API requests time out. Which endpoint-side network control should be examined?', 'The endpoint SG’s inbound listener-port permission from the caller', 'Interface ENIs use security groups.', ['A gateway endpoint’s nonexistent SG','That is the wrong endpoint mechanism.'], ['The bucket lifecycle transition','It does not allow TCP.'], ['Only account payment preferences','They do not explain this packet control.']],
    ['On-premises clients need private S3 access through VPN. A design points them at a VPC’s S3 gateway endpoint. What should change?', 'Evaluate an S3 interface endpoint with hybrid DNS and routed access', 'Remote clients cannot borrow the gateway endpoint.', ['Add another default route to the same gateway endpoint','That does not remove its connectivity limitation.'], ['Set every S3 object public','That fails the private access intent.'], ['Disable request signing','That does not establish a network path.']],
    ['S3 returns AccessDenied only after endpoint policy tightening. The same caller and object worked before. What should be inspected first?', 'The policy’s principal, action and resource scope along with other applicable denies', 'The controlled change points to authorization.', ['Increase the subnet size immediately','Address capacity does not explain the policy-correlated denial.'], ['Replace the TGW ASN','It is unrelated to S3 authorization.'], ['Assume a successful TCP connection grants GetObject','Transport does not grant object permissions.']],
    ['A vendor exposes one TCP API to 100 customers with duplicate CIDRs. Which pattern avoids customer route exchange?', 'An endpoint service and customer interface endpoints', 'PrivateLink narrows connectivity to the published service.', ['Peering every duplicate range','Peering rejects overlaps.'], ['A default route to every customer through one TGW table','Duplicate destinations remain ambiguous.'], ['A gateway endpoint for arbitrary vendor TCP','Gateway endpoints are not arbitrary service publishers.']],
    ['A PrivateLink connection remains pending acceptance. The target is healthy. Which owner should act next?', 'The service provider, after verifying the intended consumer request', 'Connection acceptance is a provider onboarding step when required.', ['The S3 storage lifecycle owner','S3 lifecycle is unrelated.'], ['Every customer must renumber first','Overlap is supported by this pattern.'], ['Disable all NLB health checks','Target health is not the stated blocker.']],
    ['A private API accepts another customer’s invoice identifier and returns its data. What is the primary defect?', 'Missing application tenant authorization', 'Private transport does not establish access to another tenant’s records.', ['Too few gateway endpoints','Endpoint count cannot authorize invoice ownership.'], ['CIDRs overlap','Overlap does not explain application data authorization.'], ['The API should trust all private callers','That is the defective assumption.']],
    ['Two accounts select AZ name us-east-1a for a PrivateLink deployment. What should be verified?', 'Whether their selected AZ IDs match the intended physical zone', 'AZ names can map differently between accounts.', ['That names always guarantee identical physical zones','This assumption is not safe across accounts.'], ['That both VPCs use a public DNS zone only','That does not verify placement.'], ['That every target uses a public IP','The service pattern does not require this.']],
    ['Using fictional lesson rates, an endpoint costs $14.40 fixed plus $0.01/GB; avoided NAT is $0.05/GB. At 100 GB, what is true?', 'The endpoint costs $10.40 more in this incremental model', '15.40 − 5.00 = 10.40.', ['The endpoint saves all NAT hourly costs','The model keeps NAT for other traffic.'], ['The endpoint saves $100','That is not the stated arithmetic.'], ['Costs are equal','The break-even is 360 GB.'], '4.4'],
    ['An egress consolidation saves gateway hours but adds large TGW processing volume. How should it be assessed?', 'Compare total incremental path cost under the same availability requirements', 'Gateway count alone is insufficient.', ['Accept it because central always means cheaper','Centralization adds costs too.'], ['Ignore response bytes','They can dominate traffic.'], ['Remove redundant AZ capacity without reviewing the SLO','That changes the availability requirement.'], '4.4'],
    ['A cost proposal assumes all S3 calls use a free gateway endpoint, including calls from remote VPCs through TGW. What is wrong?', 'Those remote clients cannot consume that gateway endpoint through TGW', 'Local gateway endpoints or an appropriate paid remote-access design are needed.', ['S3 gateway endpoints always have ENI-hour charges','They do not.'], ['TGW routes are identical to DNS records','Routing and DNS are separate.'], ['Endpoint policies remove S3 request charges','Policies do not change service billing.'], '4.4'],
    ['A team removes NAT after enabling S3 access and loses package downloads. Which requirement was missed?', 'Non-S3 dependencies still need a supported egress path', 'A service-specific endpoint is not general internet access.', ['S3 must be made public','Public object permissions do not provide package egress.'], ['All gateway endpoints proxy arbitrary hosts','They do not.'], ['Route-table names must match hostnames','Names are not the forwarding mechanism.'], '4.4'],
    ['A service invocation is IAM-authorized, but a business rule rejects a refund. What is the correct interpretation?', 'Network/service invocation permission and business authorization are separate', 'An allowed transport request can still be denied by the application.', ['All business actions must be allowed after IAM','That overstates invocation permission.'], ['Lattice can never forward an HTTP request','It supports application service access.'], ['Add a public IP to bypass the rule','That does not fix authorization.']],
    ['A Lattice rollout has resolvable DNS and valid signatures but no healthy targets. Which layer should be repaired?', 'Target registration, health checks and application readiness', 'The observed problem is the forwarding/runtime target.', ['Loosen the caller IAM policy first','The signature and authorization path are not the stated failure.'], ['Create a peer for every service by default','That does not start unhealthy targets.'], ['Disable business logging','That removes useful evidence.']],
    ['A resource configuration is added to a Lattice service network. Which assumption must be rejected?', 'The service-network auth policy automatically governs the resource configuration', 'AWS documents a distinct policy boundary for resource configurations.', ['The chosen access model needs review','That is appropriate.'], ['The actual protocol needs compatibility checks','That is appropriate.'], ['Positive and negative access tests are useful','They are useful verification.']],
    ['Which choice keeps Lattice awareness in perspective for this module?', 'Learn its service model while retaining distinct peering, TGW and endpoint decisions', 'Each answers a different connectivity requirement.', ['Replace every TGW with Lattice regardless of traffic','Generic transit requirements may remain.'], ['Treat Lattice as an S3 gateway endpoint alias','They are different services.'], ['Assume awareness lessons guarantee complete exam coverage','The curriculum makes no such guarantee.']]
  ];
  var quiz = {passMark: 70, questions: quizRows.map(function(r,i) {
    return q('M10-Q' + String(i+1).padStart(2,'0'), r[0], [[r[1],true,r[2]], [r[3][0],false,r[3][1]], [r[4][0],false,r[4][1]], [r[5][0],false,r[5][1]]], r[6] || '3.4', i >= 20 ? 400 : 300);
  })};
  // Include multiple-response scenarios, scored all-or-nothing by the shared quiz UI.
  quiz.questions[4] = q('M10-Q05', 'Dev may reach Shared but not Prod. Which TWO changes support that TGW design?', [
    ['Associate Dev with an ingress table routing to Shared but not Prod',true,'Association determines the routing view for Dev traffic.'],
    ['Provide Shared with an explicit return path to Dev',true,'Allowed requests still require replies.'],
    ['Propagate Prod into every TGW table',false,'That undermines the intended route boundary.'],
    ['Leave a fallback route reaching Prod unreviewed',false,'An alternate matching path can defeat isolation.'],
    ['Treat route separation as complete application authentication',false,'Application and security controls remain necessary.']
  ], '1.2');
  quiz.questions[11] = q('M10-Q12', 'An endpoint policy change correlates with S3 AccessDenied. Which TWO investigations are appropriate?', [
    ['Compare endpoint action/resource scope with the exact request',true,'The changed filter may exclude the operation.'],
    ['Inspect the caller identity and applicable resource/organization denies',true,'Endpoint access does not replace the other permission boundaries.'],
    ['Assume TCP success grants GetObject',false,'Transport reachability does not grant service permissions.'],
    ['Change the TGW ASN immediately',false,'It does not explain this authorization response.'],
    ['Make the test bucket public to mask the problem',false,'That does not diagnose the controlled policy change.']
  ], '1.2');
  quiz.questions[15] = q('M10-Q16', 'A vendor onboards a second account to its private API. Which TWO independent checks are needed?', [
    ['Compare supported AZ IDs for endpoint placement',true,'AZ names can map differently across accounts.'],
    ['Test application tenant authorization after endpoint acceptance',true,'Accepted transport does not grant access to every tenant.'],
    ['Assume accepted means all targets are healthy',false,'Target health requires separate checks.'],
    ['Require renumbering solely because the CIDRs overlap',false,'The described PrivateLink pattern supports overlap.'],
    ['Expose every provider subnet through the endpoint',false,'This is a service boundary, not general subnet routing.']
  ], '1.2');
  quiz.questions[22] = q('M10-Q23', 'A Lattice review covers services and resource configurations. Which TWO statements are sound?', [
    ['Verify controls for the specific access model',true,'Service and resource access do not share every policy assumption.'],
    ['Keep business authorization within the application',true,'Allowed invocation does not authorize every business operation.'],
    ['Service-network auth policies automatically cover resource configurations',false,'They do not apply to resource configurations.'],
    ['Healthy DNS guarantees healthy targets',false,'Target readiness is independent.'],
    ['NONE mode provides IAM authentication automatically',false,'That mode does not establish IAM authentication.']
  ], '1.2', 400);
  var labs = [{
    id: 'L10', title: 'Transit Gateway routing and evidence-backed S3 NAT bypass', level: 300, duration: '120–150 min',
    cost: 'Paid sandbox: TGW attachments, EC2/EBS, NAT, public IPv4, Flow Logs and S3 usage; price your Region before starting',
    objective: 'Connect two disposable VPCs through TGW, diagnose a missing return route, and correlate routing, S3 requests and Flow Logs before and after gateway-endpoint activation.',
    warning: 'No AWS resources are created by this LMS. The author has not deployed this lab. Use only a dedicated approved sandbox; set a deletion time and budget notifications. Notifications do not cap charges. Completion is self-reported; the offline checker validates a plan only.',
    steps: [
      {id:'s1',title:'Read scope, cost and recovery requirements',html:'<p>Read the complete <a href="labs/m10/README.md">L10 runbook</a> before provisioning. Verify account/Region and record an owner, expiry and resource inventory. Keep an operator session outside the worker data path.</p>'},
      {id:'s2',title:'Validate and break the offline routing model',html:'<p>Download <a href="labs/m10/network-plan.json" download>network-plan.json</a> and <a href="labs/m10/check_plan.py" download>check_plan.py</a>. Run the checker; remove a return route and verify failure. Restore it. The worksheet is not a deployment tool.</p>'},
      {id:'s3',title:'Build two non-overlapping VPCs',html:'<p>Follow the subnet/table inventory in the runbook. Create A and B with explicit subnet route associations; A includes a private worker subnet and a public NAT subnet. Keep B free of an internet default route. Record actual resource IDs.</p>'},
      {id:'s4',title:'Configure explicit Transit Gateway routing',html:'<p>Disable default association/propagation. Create attachments covering the chosen workload AZ, one TGW table and explicit routes for A and B. Associate both attachments and add each remote CIDR route to the corresponding workload VPC table.</p>'},
      {id:'s5',title:'Establish controlled workload and administration access',html:'<p>Create the disposable EC2 instances with the runbook’s narrow TCP 8000 test and management access. A uses NAT-backed Session Manager; B boots a test service from user data and needs no interactive administration. Verify both interfaces, addresses and instance identities.</p>'},
      {id:'s6',title:'Prove and break the TGW return path',html:'<p>Request B’s test page from A. Remove only B’s VPC return route, repeat a bounded request, then restore the exact route and verify recovery. Record timestamps and both routing layers. Keep rollback in the external operator console.</p>'},
      {id:'s7',title:'Record the pre-endpoint S3 baseline',html:'<p>Create a disposable same-Region bucket and small object. Enable Flow Logs on A’s worker and NAT interfaces with the custom fields in the runbook. Read the object using the instance role before creating the gateway endpoint; retain request timestamps and logs.</p>'},
      {id:'s8',title:'Activate and verify the S3 gateway endpoint',html:'<p>Associate only the intended A worker route table. Reconnect and repeat the same object read. Inspect the service prefix route, Flow Logs and a narrowly scoped source-endpoint policy trial. Use the independent operator session for rollback.</p>'},
      {id:'s9',title:'Interpret evidence and endpoint locality',html:'<p>Use the evidence matrix to distinguish observed requests, route configuration and logging gaps. B cannot borrow A’s S3 gateway endpoint through TGW. Do not count absent NAT records alone as proof of bypass.</p>'},
      {id:'s10',title:'Clean up and verify inventory',html:'<p>Follow the runbook dependency order to delete only recorded lab resources, including NAT, its EIP, TGW attachments/TGW, compute, endpoints, bucket, logs and lab-owned roles. Verify deletion after asynchronous operations and review delayed charges.</p>'}
    ],
    drills: [
      {id:'L10-d1',q:'Can a route worksheet passing offline prove AWS connectivity? yes/no',answers:['no'],explain:'No resources, policies or packets are inspected.'},
      {id:'L10-d2',q:'Does a missing NAT Flow Log record alone prove S3 bypass? yes/no',answers:['no'],explain:'Collection delays and skipped records require corroboration.'},
      {id:'L10-d3',q:'Can VPC B consume A’s S3 gateway endpoint over TGW? yes/no',answers:['no'],explain:'Gateway endpoint access cannot be extended through TGW.'},
      {id:'L10-d4',q:'Which S3 request-context key identifies the VPC endpoint? Include aws: prefix.',answers:['aws:sourcevpce'],explain:'aws:SourceVpce can constrain the specific object-read trial.'}
    ],
    validate:'<p>Retain before/failure/recovery HTTP results; both VPC and TGW route snapshots; S3 object-read timestamps; endpoint associations; tuple-correlated Flow Logs with log-status; and the scoped SourceVpce trial result. Mark missing evidence as inconclusive. Offline plan success is not deployed validation.</p>',
    cleanup:'<p>Use the runbook’s inventory-driven cleanup, wait for NAT and TGW attachment deletion, release the lab EIP, remove lab-only logs/storage/roles, and verify no lab-owned billable resources remain. Incurred charges remain payable.</p>'
  }];
  window.LMS_MODULES.M10 = {
    summary: 'Choose and troubleshoot private connectivity across VPCs and services. Six lessons trace peering, Transit Gateway, endpoints, PrivateLink, path costs and VPC Lattice, with 12 diagrams and a learner-run routing/NAT-bypass lab.',
    objectives: ['Select connectivity from traffic and address requirements','Trace forward and return routes across VPC and TGW tables','Separate private network access from service authorization','Compare path costs without sacrificing availability','Collect defensible routing and request evidence'],
    review: {version:'m10-1',reviewedAt:'2026-10-09',nextReview:'2027-01-09',scope:'Official-source review and local content/worksheet checks. The AWS lab has not been deployed by the author; learner cloud evidence and completion are self-reported. Cost examples use invented rates. VPC Lattice is awareness enrichment, not a promise of exam coverage.',sources:['peering','tgw','gateway','service','lattice'].map(function(k){return {title:refs[k][0],url:refs[k][1]};})},
    lessons: lessons, quiz: quiz, labs: labs, flashcards: flashcards
  };
})();
