#!/usr/bin/env python3
"""Generate lms/content/catalog.js from LMS_PLAN.md (stdlib only).

Usage:  python3 lms/tools/build_catalog.py
Re-run whenever the curriculum in LMS_PLAN.md changes.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "LMS_PLAN.md"
OUT = ROOT / "lms" / "content" / "catalog.js"


def plain(s):
    s = re.sub(r"\*\*(.*?)\*\*", r"\1", s)
    s = re.sub(r"\*(.*?)\*", r"\1", s)
    s = s.replace("`", "")
    return s.strip()


def cells(line):
    return [plain(c) for c in line.strip().strip("|").split("|")]


def expand_prereqs(text):
    """'M05, M09 (recommended)' -> ['M05'];  'M05–M34' -> ['M05', ..., 'M34']."""
    ids = []
    for part in re.split(r",|\+", text):
        if "recommended" in part:
            continue
        rng = re.search(r"M(\d{2})\s*[–-]\s*M(\d{2})", part)
        if rng:
            ids += [f"M{i:02d}" for i in range(int(rng.group(1)), int(rng.group(2)) + 1)]
        else:
            ids += re.findall(r"M\d{2}", part)
    return ids


md = SRC.read_text(encoding="utf-8").splitlines()
tracks, paths = [], []
track = module = None

for i, line in enumerate(md):
    if line.startswith("| **P") and "–" in line:
        c = cells(line)
        pid, name = c[0].split("–", 1)
        paths.append({"id": pid.strip(), "name": name.strip(), "modules": c[1], "hours": c[2], "outcome": c[3]})
        continue

    m = re.match(r"^### Track ([A-Z]) – (.*)$", line)
    if m:
        track = {"id": m.group(1), "title": plain(m.group(2)), "modules": []}
        tracks.append(track)
        continue

    m = re.match(r"^#### (M\d{2}) – (.*)$", line)
    if m and track:
        meta = plain(md[i + 2]) if i + 2 < len(md) else ""
        parts = [p.strip() for p in meta.split("·")]
        module = {
            "id": m.group(1),
            "title": plain(m.group(2)),
            "track": track["id"],
            "levels": parts[0].replace("Level ", "") if parts else "",
            "hours": parts[1] if len(parts) > 1 else "",
            "exam": next((p[6:] for p in parts if p.startswith("Exam: ")), ""),
            "prereqs": [],
            "lessons": [],
        }
        pre = next((p for p in parts if p.startswith("Prerequisites")), "")
        module["prereqs"] = [p for p in expand_prereqs(pre) if p != module["id"]]
        track["modules"].append(module)
        continue

    if module and line.startswith("|"):
        c = cells(line)
        lm = re.match(r"^(M\d{2}\.\d{2}) (.*)$", c[0])
        if lm and lm.group(1).startswith(module["id"]):
            if len(c) >= 3 and re.fullmatch(r"\d{3}|–", c[1]):
                level, concepts = c[1], c[2]
            else:  # case-study table: | id title | concepts | services | source |
                level = "300"
                concepts = f"{c[1]} · Services: {c[2]}" + (f" · Source: {c[3]}" if len(c) > 3 else "")
            module["lessons"].append({"id": lm.group(1), "title": lm.group(2), "level": level, "concepts": concepts})
        elif c[0].startswith("C") and "–" in c[0] and module["id"] == "M44":
            cid, ctitle = c[0].split("–", 1)
            module["lessons"].append({
                "id": f"M44.{len(module['lessons']) + 1:02d}",
                "title": f"Capstone {cid.strip()}: {ctitle.strip()}",
                "level": "400",
                "concepts": f"{c[1]} · Assessed on: {c[2]}",
            })

catalog = {"generatedFrom": "LMS_PLAN.md", "paths": paths, "tracks": tracks}
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    "/* AUTO-GENERATED by lms/tools/build_catalog.py from LMS_PLAN.md. Do not edit by hand. */\n"
    "window.LMS_CATALOG = " + json.dumps(catalog, ensure_ascii=False, indent=1) + ";\n",
    encoding="utf-8",
)
n_mod = sum(len(t["modules"]) for t in tracks)
n_les = sum(len(m["lessons"]) for t in tracks for m in t["modules"])
print(f"tracks={len(tracks)} modules={n_mod} lessons={n_les} paths={len(paths)} -> {OUT}")
